;;; opencode-shell-recovery-test.el --- Bounded retry tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'opencode-shell-recovery)

(ert-deftest opencode-shell-recovery-bounds-retries-after-five-failures ()
  (let ((opencode-shell-recovery--states (make-hash-table :test #'equal))
        timers delays (wakes 0))
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (delay _repeat callback &rest args)
                 (push delay delays)
                 (let ((timer (list 'timer callback args)))
                   (push timer timers)
                   timer)))
              ((symbol-function 'timerp)
               (lambda (value) (eq (car-safe value) 'timer)))
              ((symbol-function 'cancel-timer) #'ignore))
      (dotimes (index 5)
        (opencode-shell-recovery-failed
         'remote (lambda () (cl-incf wakes)) (lambda () t))
        (when (< index 4)
          (let ((timer (car timers)))
            (apply (nth 1 timer) (nth 2 timer)))))
      (should (equal (nreverse delays) '(1 2 4 8)))
      (should (opencode-shell-recovery-exhausted-p 'remote))
      (opencode-shell-recovery-failed 'remote #'ignore (lambda () t))
      (should (= (length timers) 4))
      (should (= wakes 4))
      (opencode-shell-recovery-manual-reset 'remote)
      (should-not (opencode-shell-recovery-exhausted-p 'remote))
      (opencode-shell-recovery-failed 'remote #'ignore (lambda () t))
      (should (equal (car delays) 1))
      (opencode-shell-recovery-success 'remote)
      (should-not (opencode-shell-recovery-offline-p 'remote)))))

(ert-deftest opencode-shell-recovery-attempt-deadline-ignores-stale-callback ()
  (let ((opencode-shell-recovery--states (make-hash-table :test #'equal))
        timers cancelled (expired 0))
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (_delay _repeat callback &rest args)
                 (let ((timer (list 'timer callback args)))
                   (push timer timers)
                   timer)))
              ((symbol-function 'timerp)
               (lambda (value) (eq (car-safe value) 'timer)))
              ((symbol-function 'cancel-timer)
               (lambda (timer) (push timer cancelled))))
      (opencode-shell-recovery-watch-attempt 'remote (lambda () (cl-incf expired)))
      (let ((old (car timers)))
        (opencode-shell-recovery-watch-attempt 'remote (lambda () (cl-incf expired)))
        (should (memq old cancelled))
        (apply (nth 1 old) (nth 2 old))
        (should (= expired 0))
        (let ((current (car timers)))
          (apply (nth 1 current) (nth 2 current))
          (apply (nth 1 current) (nth 2 current))
          (should (= expired 1)))))))

(ert-deftest opencode-shell-recovery-no-demand-cancels-pending-retry ()
  (let ((opencode-shell-recovery--states (make-hash-table :test #'equal))
        timer woke)
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (_delay _repeat callback &rest args)
                 (setq timer (cons callback args))
                 nil)))
      (opencode-shell-recovery-failed 'remote (lambda () (setq woke t))
                                      (lambda () nil))
      (apply (car timer) (cdr timer))
      (should-not woke)
      (should-not (gethash 'remote opencode-shell-recovery--states)))))

(provide 'opencode-shell-recovery-test)
;;; opencode-shell-recovery-test.el ends here
