;;; opencode-shell-test.el --- Tests for opencode-shell -*- lexical-binding: t; -*-

;; Copyright (C) 2026
;; Author: opencode-shell contributors
;; Package-Requires: ((emacs "27.1"))

;;; Code:

(require 'ert)
(require 'opencode-shell)
(require 'opencode-shell-acceptance-test)

(defvar opencode-shell-test--local-profile)
(defvar opencode-shell-test--remote-profile)

(ert-deftest opencode-shell-query-and-payload ()
  (should (equal (opencode-shell--query '((directory . "/tmp/a b") (empty)))
                 "directory=%2Ftmp%2Fa%20b"))
  (with-temp-buffer
    (setq-local opencode-shell--selected-model
                '((providerID . "openai") (modelID . "gpt")))
    (setq-local opencode-shell--selected-agent "build")
    (let ((body (opencode-shell--prompt-body "안녕")))
      (should (equal (alist-get 'agent body) "build"))
      (should (equal (alist-get 'model body) opencode-shell--selected-model))
      (should (equal (alist-get 'text (aref (alist-get 'parts body) 0)) "안녕")))))

(ert-deftest opencode-shell-session-normalization-and-filter ()
  (let* ((old '((id . "old") (title . "Alpha") (time (updated . 1000))))
         (new '((id . "new") (title . "Beta") (directory . "/work")
                (time (updated . 3000)))))
    (with-temp-buffer
      (setq-local opencode-shell--sessions
                  (opencode-shell--normalize-sessions (list old new old)))
      (should (equal (mapcar (lambda (x) (opencode-shell--get x 'id))
                             opencode-shell--sessions) '("new" "old")))
      (setq-local opencode-shell--filter "work")
      (should (equal (mapcar #'car (opencode-shell--session-entries)) '("new"))))))

(ert-deftest opencode-shell--open-at-point-forwards-explicit-directory ()
  (with-temp-buffer
    (insert (propertize "one" 'tabulated-list-id "s1"))
    (goto-char (point-min))
    (setq-local opencode-shell--directory "/list/root")
    (setq-local opencode-shell--sessions
                '(((id . "s1") (directory . "/scope/exact"))))
    (let (opened)
      (cl-letf (((symbol-function 'opencode-shell-open-session)
                 (lambda (id directory) (setq opened (list id directory)))))
        (opencode-shell--open-at-point)
        (should (equal opened '("s1" "/scope/exact")))))))

(ert-deftest opencode-shell-browser-create-reuses-start-session-flow ()
  (with-temp-buffer
    (setq-local opencode-shell--profile opencode-shell-test--remote-profile)
    (let (started)
      (cl-letf (((symbol-function 'opencode-shell--start-session)
                 (lambda (profile directory) (setq started (list profile directory)))))
        (opencode-shell--create-session)
        (should (equal started
                       (list opencode-shell-test--remote-profile nil)))))))

(ert-deftest opencode-shell-start-session-reads-directory-and-creates-titleless-session ()
  (let ((profile opencode-shell-test--local-profile) created)
    (cl-letf (((symbol-function 'opencode-shell--current-server-directory)
               (lambda (_) "/server/chosen/"))
              ((symbol-function 'opencode-shell--start-server)
               (lambda (value callback) (funcall callback value)))
              ((symbol-function 'opencode-shell--create-and-open-session)
               (lambda (value directory) (setq created (list value directory)))))
      (opencode-shell--start-session profile)
      (should (equal created (list profile "/server/chosen/"))))))

(ert-deftest opencode-shell-create-and-open-session-omits-title ()
  (let ((profile opencode-shell-test--remote-profile) request opened)
    (cl-letf (((symbol-function 'opencode-shell--request)
               (lambda (method path callback &optional body)
                 (setq request (list method path body))
                 (funcall callback '((id . "new")))))
              ((symbol-function 'opencode-shell-open-session)
               (lambda (id directory value)
                 (setq opened (list id directory value)))))
      (opencode-shell--create-and-open-session profile "/srv/chosen/")
      (should (equal request '("POST" "/session" nil)))
      (should (equal opened (list "new" "/srv/chosen/" profile))))))

(ert-deftest opencode-shell-model-agent-normalization ()
  (let* ((models (opencode-shell--normalize-models
                  '((all . (((id . "p") (models . (("m" . ((id . "m")))))))))))
         (agents (opencode-shell--normalize-agents
                  '(((name . "build")) ((name . "plan"))))))
    (should (equal (caar models) "p/m"))
    (should (equal (mapcar #'car agents) '("build" "plan")))
    (should (equal (opencode-shell--preserve-choice
                    '((providerID . "p") (modelID . "m")) models)
                   '((providerID . "p") (modelID . "m"))))))

(ert-deftest opencode-shell-model-agent-normalization-filters-server-scope ()
  (let ((models
         (opencode-shell--normalize-models
          '((connected . ("ready"))
            (all . (((id . "ready")
                     (models . (("one" . ((id . "one"))))))
                    ((id . "other")
                     (models . (("two" . ((id . "two")))))))))))
        (agents
         (opencode-shell--normalize-agents
          '(((name . "build") (mode . "primary"))
            ((name . "hidden") (mode . "primary") (hidden . t))
            ((name . "worker") (mode . "subagent"))))))
    (should (equal (mapcar #'car models) '("ready/one")))
    (should (equal (mapcar #'car agents) '("build")))
    (should-not
     (opencode-shell--normalize-models
      '((connected . ())
         (all . (((id . "ready")
                  (models . (("one" . ((id . "one")))))))))))))

(ert-deftest opencode-shell-model-object-and-session-display ()
  (let ((models (opencode-shell--normalize-models
                 '((all . (((id . "p")
                            (models . (((id . "one"))
                                       ("two" . ((name . "Two"))))))))))))
    (should (equal (mapcar #'car models) '("p/one" "p/two")))
    (should (equal (mapcar #'car
                           (opencode-shell--normalize-models
                            '((providers . (((id . "q")
                                             (models . ((three . ((name . "Three")))))))))))
                   '("q/three")))
    (should (equal (aref (cadr (opencode-shell--session-row
                                '((id . "s") (model . ((providerID . "p")
                                                       (modelID . "one")))))) 3)
                   "p/one"))
    (should (equal (aref (cadr (opencode-shell--session-row
                                '((id . "s") (model . "p/two")))) 3)
                   "p/two"))))

(ert-deftest opencode-shell-http-status-and-bounded-errors ()
  (should (<= (string-width (opencode-shell--bounded-error
                             (concat "bad\n" (make-string 500 ?x)))) 300))
  (let (called messages)
    (cl-letf (((symbol-function 'url-retrieve)
               (lambda (_ callback &rest _)
                 (with-temp-buffer
                   (insert "HTTP/1.1 204 No Content\r\n\r\n")
                   (setq-local url-http-response-status 204)
                   (funcall callback nil))))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (push (apply #'format format-string args) messages))))
      (opencode-shell--request "GET" "/ok" (lambda (value) (setq called (list value))))
      (should (equal called '(nil)))
      (setq called nil)
      (cl-letf (((symbol-function 'url-retrieve)
                 (lambda (_ callback &rest _)
                   (with-temp-buffer
                     (insert "HTTP/1.1 300 Multiple\r\n\r\nnot success")
                     (setq-local url-http-response-status 300)
                     (funcall callback nil)))))
        (opencode-shell--request "GET" "/bad" (lambda (_) (setq called t))))
      (should-not called)
      (should (string-match-p "HTTP 300: not success" (car messages))))))

(ert-deftest opencode-shell-question-multiple-custom-semantics ()
  (let ((item '((id . "q")
                (questions . (((question . "Single choice")
                               (options . (((label . "A")) ((label . "B")))))
                              ((question . "Single custom") (custom . t)
                               (options . (((label . "C")))))
                              ((question . "Multiple choice") (multiple . t)
                               (options . (((label . "D")) ((label . "E")))))
                              ((question . "Multiple custom") (multiple . t)
                               (custom . t) (options . (((label . "F")))))))))
        requests completion-calls)
    (cl-letf (((symbol-function 'opencode-shell--choose-pending)
               (lambda (_ callback) (funcall callback item)))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
              ((symbol-function 'completing-read)
               (lambda (prompt collection _predicate require-match &rest _)
                 (push (list 'single prompt collection require-match)
                       completion-calls)
                 (if require-match "B" "own single")))
              ((symbol-function 'completing-read-multiple)
               (lambda (prompt collection _predicate require-match &rest _)
                 (push (list 'multiple prompt collection require-match)
                       completion-calls)
                 (if require-match '("E" "D") '("own first" "F" "own last"))))
              ((symbol-function 'opencode-shell--request)
               (lambda (method path _callback &optional body &rest _)
                 (push (list method path body) requests))))
      (opencode-shell--questions)
      (should (equal (caddar requests)
                     '((answers . [["B"] ["own single"] ["E" "D"]
                                   ["own first" "F" "own last"]]))))
      (should (equal (json-serialize (caddar requests))
                     "{\"answers\":[[\"B\"],[\"own single\"],[\"E\",\"D\"],[\"own first\",\"F\",\"own last\"]]}"))
      (should
       (equal (nreverse completion-calls)
              '((single "Single choice [A, B]: " ("A" "B") t)
                (single "Single custom [C]: " ("C") nil)
                (multiple "Multiple choice [D, E]: " ("D" "E") t)
                (multiple "Multiple custom [F]: " ("F") nil)))))))

(ert-deftest opencode-shell-question-rejection ()
  (let ((item '((id . "q") (question . "Question"))) requests)
    (cl-letf (((symbol-function 'opencode-shell--choose-pending)
               (lambda (_ callback) (funcall callback item)))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) nil))
              ((symbol-function 'opencode-shell--request)
               (lambda (method path _callback &optional body &rest _)
                 (push (list method path body) requests))))
      (opencode-shell--questions)
      (should (equal (cadar requests) "/question/q/reject")))))

(ert-deftest opencode-shell-permission-replies-and-presentation ()
  (let ((item '((id . "p1") (permission . "bash")
                (patterns . ("git status" "git diff"))
                (always . ("git *"))
                (tool . ((name . "shell") (command . "git status")))
                (metadata . ((cwd . "/work") (reason . "inspect")))))
        requests confirmations)
    (cl-letf (((symbol-function 'opencode-shell--permission-at-point)
               (lambda () item))
              ((symbol-function 'yes-or-no-p)
               (lambda (shown) (push shown confirmations) t))
              ((symbol-function 'opencode-shell--request)
               (lambda (method path _callback &optional body &rest _)
                 (push (list method path body) requests))))
      (opencode-shell--permission-allow-once)
      (should (equal (car requests)
                     '("POST" "/permission/p1/reply" ((reply . "once")))))
      (should (string-match-p "bash.*git status.*git diff"
                              (opencode-shell--permission-description item)))
      (should-not confirmations)

      (setq requests nil opencode-shell--permission-sending nil)
      (opencode-shell--permission-reject)
      (should (equal (caddar requests) '((reply . "reject"))))
      (should-not confirmations)

      (setq requests nil opencode-shell--permission-sending nil)
      (opencode-shell--permission-allow-always)
      (should (equal (caddar requests) '((reply . "always"))))
      (should (string-match-p "Always allow" (car confirmations)))

      (setq requests nil confirmations nil opencode-shell--permission-sending nil)
      (cl-letf (((symbol-function 'yes-or-no-p)
                 (lambda (shown) (push shown confirmations) nil)))
        (should-error (opencode-shell--permission-allow-always)
                      :type 'user-error))
      (should confirmations)
      (should-not requests))))

(ert-deftest opencode-shell-permission-pending-label-shows-patterns ()
  (let (candidates)
    (cl-letf (((symbol-function 'opencode-shell--request)
               (lambda (_method _path callback &rest _)
                 (funcall callback
                          '(((id . "p2") (permission . "edit")
                             (patterns . ("src/a.el" "src/b.el")))))))
              ((symbol-function 'completing-read)
               (lambda (_prompt table &rest _)
                 (setq candidates (mapcar #'car table))
                 (caar table))))
      (opencode-shell--choose-pending "permission" #'ignore)
      (should (string-match-p
               "p2: edit.*patterns=.*src/a.el.*src/b.el" (car candidates))))))

(ert-deftest opencode-shell-permission-context-is-bounded ()
  (let ((description
         (opencode-shell--permission-description
          `((permission . "read")
            (metadata . ((payload . ,(make-string 1000 ?x))))))))
    (should (< (length description) 250))
    (should (string-match-p "metadata=" description))))

(ert-deftest opencode-shell-inline-permission-preserves-composer-and-replies ()
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--session-id "s")
    (insert "draft")
    (goto-char (+ opencode-shell--composer-start 2))
    (opencode-shell--receive-permissions
     '(((id . "missing") (permission . "write"))
       ((id . "other") (sessionID . "x") (permission . "read"))
       ((id . "p") (sessionID . "s") (permission . "bash")
        (patterns . ("git status")))))
    (should (= (length opencode-shell--permissions) 1))
    (should (equal (opencode-shell--composer-text) "draft"))
    (should (= (- (point) opencode-shell--composer-start) 2))
    (goto-char opencode-shell--permission-begin)
    (should (search-forward "PERMISSION" opencode-shell--permission-end t))
    (should (search-forward "git status" opencode-shell--permission-end t))
    (opencode-shell--receive-permissions opencode-shell--permissions)
    (goto-char (point-min))
    (should (= (how-many "PERMISSION" (point-min) (point-max)) 1))
    (should (= (how-many "Prompt>" (point-min) (point-max)) 1))
    (let (request callback)
      (cl-letf (((symbol-function 'opencode-shell--request)
                 (lambda (method path success &optional body &rest _)
                   (setq request (list method path body) callback success))))
        (goto-char opencode-shell--permission-begin)
        (opencode-shell--permission-allow-once)
        (should (equal request '("POST" "/permission/p/reply" ((reply . "once")))))
        (should-error (opencode-shell--permission-reject) :type 'user-error)
        (funcall callback nil)
        (should-not opencode-shell--permissions)
        (should (equal (opencode-shell--composer-text) "draft"))))))

(ert-deftest opencode-shell-polling-generation-and-capabilities ()
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--session-id "s" opencode-shell--generation 1)
    (let (requests stale)
      (cl-letf (((symbol-function 'opencode-shell--request)
                 (lambda (_ path callback &optional _body _params error-callback)
                   (push (list path callback error-callback) requests))))
        (opencode-shell--resync)
        (should (= (length requests) 4))
        (should opencode-shell--capabilities-loading)
        (should-not opencode-shell--capabilities-loaded)
        ;; A poll while the capability pair is pending must not overlap it.
        (opencode-shell--resync)
        (should (= (length requests) 4))
        (funcall (cadr (assoc "/provider" requests)) '((providers . nil)))
        (should-not opencode-shell--capabilities-loaded)
        (funcall (cadr (assoc "/agent" requests)) nil)
        (should opencode-shell--capabilities-loaded)
        (should-not opencode-shell--capabilities-loading)
        (let ((old (cadr (assoc "/session/s/message" requests))))
          (setq opencode-shell--generation 2
                opencode-shell--in-flight '((messages . t)) requests nil)
          (cl-letf (((symbol-function 'opencode-shell--render-messages)
                     (lambda (_) (setq stale t))))
            (funcall old nil))
          (should-not stale)
          (should (alist-get 'messages opencode-shell--in-flight))
          (setq opencode-shell--in-flight nil))
        (opencode-shell--resync)
        (should (equal (mapcar #'car requests)
                       '("/permission" "/session/s/message")))))))

(ert-deftest opencode-shell-capabilities-retry-after-transient-failure ()
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--session-id "s" opencode-shell--generation 1)
    (let (requests)
      (cl-letf (((symbol-function 'opencode-shell--request)
                 (lambda (_method path callback &optional _body _params error-callback)
                   (push (list path callback error-callback) requests))))
        (opencode-shell--resync)
        (funcall (nth 2 (assoc "/provider" requests)))
        (should opencode-shell--capabilities-loading)
        (funcall (cadr (assoc "/agent" requests)) nil)
        (should-not opencode-shell--capabilities-loading)
        (should-not opencode-shell--capabilities-loaded)
        (setq requests nil)
        (opencode-shell--resync)
        ;; The still-pending message poll remains guarded; only the failed
        ;; capability batch is retried.
        (should (= (length requests) 2))
        (should (assoc "/provider" requests))
        (should (assoc "/agent" requests))))))

(ert-deftest opencode-shell-poll-error-releases-guard ()
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--generation 7)
    (let (failed)
      (cl-letf (((symbol-function 'opencode-shell--request)
                 (lambda (_method _path _callback &optional _body _params error-callback)
                   (setq failed error-callback))))
        (opencode-shell--guarded-request 'messages "GET" "/message" #'ignore)
        (should (alist-get 'messages opencode-shell--in-flight))
        (funcall failed)
        (should-not (alist-get 'messages opencode-shell--in-flight))))))

(ert-deftest opencode-shell-request-ignores-killed-origin ()
  (let ((origin (generate-new-buffer " *oc-dead-origin*")) retrieve-callback called)
    (cl-letf (((symbol-function 'url-retrieve)
               (lambda (_url callback &rest _)
                 (setq retrieve-callback callback))))
      (with-current-buffer origin
        (opencode-shell--request "GET" "/late" (lambda (_) (setq called t))))
      (kill-buffer origin)
      (with-temp-buffer
        (insert "HTTP/1.1 200 OK\r\n\r\n[]")
        (setq-local url-http-response-status 200)
        (funcall retrieve-callback nil))
      (should-not called))))

(ert-deftest opencode-shell-reopen-keeps-one-timer ()
  (let (timers cancelled)
    (cl-letf (((symbol-function 'pop-to-buffer) #'ignore)
              ((symbol-function 'opencode-shell--resync) #'ignore)
              ((symbol-function 'run-at-time)
               (lambda (&rest _) (let ((timer (list 'timer))) (push timer timers) timer)))
              ((symbol-function 'timerp) (lambda (value) (eq (car-safe value) 'timer)))
              ((symbol-function 'cancel-timer) (lambda (timer) (push timer cancelled))))
      (unwind-protect
          (progn
            (opencode-shell-open-session "timer-test")
            (opencode-shell-open-session "timer-test")
            (should (= (length timers) 2))
            (should (equal cancelled (list (cadr timers)))))
        (kill-buffer "*OpenCode Shell timer-test*")))))

(ert-deftest opencode-shell-evil-setup-load-orders ()
  (let (calls)
    (cl-letf (((symbol-function 'evil-set-initial-state)
               (lambda (&rest args) (push (cons 'state args) calls)))
              ((symbol-function 'evil-define-key*)
               (lambda (&rest args) (push (cons 'key args) calls))))
      (opencode-shell--setup-evil)
      (should (= (length calls) 4)))))

(ert-deftest opencode-shell-uses-editable-base-with-native-character-input ()
  (with-temp-buffer
    (opencode-shell-mode)
    (should (derived-mode-p 'text-mode))
    (should-not (derived-mode-p 'special-mode))
    (should-not (lookup-key opencode-shell-mode-map (kbd "i")))
    (should-not (lookup-key opencode-shell-mode-map (kbd "한")))
    (should-not (fboundp 'opencode-shell-self-insert))
    (should-not (fboundp 'opencode-shell-newline))))

(ert-deftest opencode-shell-selections-are-buffer-local ()
  (let ((a (generate-new-buffer " *oc-a*")) (b (generate-new-buffer " *oc-b*")))
    (unwind-protect
        (progn
          (with-current-buffer a (opencode-shell-mode)
                               (setq opencode-shell--selected-agent "build"))
          (with-current-buffer b (opencode-shell-mode)
                               (should-not opencode-shell--selected-agent)))
      (kill-buffer a) (kill-buffer b))))

(ert-deftest opencode-shell-markdown-preserves-raw-unicode-and-fences ()
  (with-temp-buffer
    (setq font-lock-defaults '(opencode-shell-render-font-lock-keywords t))
    (let ((raw "# 제목\n\n- 목록과 **굵게** 및 [링크](https://example.com)\n\n> 원문\n\n```elisp\n(message \"안녕\")\n```\n"))
      (opencode-shell-render-insert raw)
      (should (equal (buffer-substring-no-properties (point-min) (point-max)) raw))
      (should (get-text-property (string-match "message" raw) 'face)))))

(ert-deftest opencode-shell-keymaps-and-cleanup ()
  (should (eq (lookup-key opencode-shell-mode-map (kbd "C-c C-y"))
              #'opencode-shell--permission-allow-once))
  (should (eq (lookup-key opencode-shell-mode-map (kbd "C-c C-l"))
              #'opencode-shell--permission-allow-always))
  (should (eq (lookup-key opencode-shell-mode-map (kbd "C-c C-n"))
              #'opencode-shell--permission-reject))
  (should-not (lookup-key opencode-shell-mode-map (kbd "p")))
  (should-not (fboundp 'opencode-shell-prompt))
  (should (eq (lookup-key opencode-shell-sessions-mode-map (kbd "RET"))
              #'opencode-shell--open-at-point))
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--poll-timer (run-at-time 60 nil #'ignore))
    (setq opencode-shell--generation 4
          opencode-shell--in-flight '((messages . t))
          opencode-shell--capabilities-loading t)
    (opencode-shell--cleanup)
    (should-not opencode-shell--poll-timer)
    (should-not opencode-shell--in-flight)
    (should-not opencode-shell--capabilities-loading)
    (should (= opencode-shell--generation 5))))

(ert-deftest opencode-shell-private-mode-commands-are-hidden-from-completion ()
  (dolist (command opencode-shell--mode-commands)
    (should (commandp command))
    (should-not (funcall (get command 'completion-predicate) command nil)))
  (dolist (command '(opencode-shell opencode-shell-status
                     opencode-shell-restart opencode-shell-reload))
    (should (commandp command))
    (should-not (get command 'completion-predicate)))
  (should (eq (lookup-key opencode-shell-sessions-mode-map (kbd "RET"))
              'opencode-shell--open-at-point))
  (should (eq (lookup-key opencode-shell-mode-map (kbd "C-c C-c"))
              'opencode-shell--submit)))

(defun opencode-shell-test--message (id role text &optional parent)
  "Build a minimal message envelope for conversation tests."
  `((info . ((id . ,id) (role . ,role) ,@(and parent `((parentID . ,parent)))))
    (parts . (((type . "text") (text . ,text))))))

(defun opencode-shell-test--tool-message (id parent)
  "Build a tool-only assistant envelope for conversation tests."
  `((info . ((id . ,id) (role . "assistant") (parentID . ,parent)))
    (parts . (((type . "tool") (tool . "read"))))))

(ert-deftest opencode-shell-reconciles-identical-local-prompts-in-order ()
  (with-temp-buffer
    (opencode-shell-mode)
    (let ((first (opencode-shell--make-turn :id "local-1" :user "same" :status 'waiting))
          (second (opencode-shell--make-turn :id "local-2" :user "same" :status 'waiting)))
      (setq opencode-shell--turns (list first second))
      (opencode-shell--render-messages
       (list (opencode-shell-test--message "u1" "user" "same")
             (opencode-shell-test--message "u2" "user" "same")))
      (should (= (length opencode-shell--turns) 2))
      (should (eq (nth 0 opencode-shell--turns) first))
      (should (eq (nth 1 opencode-shell--turns) second))
      (should (equal (mapcar #'opencode-shell--turn-server-user-id opencode-shell--turns)
                     '("u1" "u2"))))))

(ert-deftest opencode-shell-tool-only-assistant-keeps-turn-waiting-until-text ()
  (with-temp-buffer
    (opencode-shell-mode)
    (let ((user (opencode-shell-test--message "u1" "user" "question")))
      (opencode-shell--render-messages
       (list user (opencode-shell-test--tool-message "a1" "u1")))
      (should (eq (opencode-shell--turn-status (car opencode-shell--turns)) 'waiting))
      (should-not (opencode-shell--turn-assistant (car opencode-shell--turns)))
      (should (equal opencode-shell--request-status "waiting"))
      (opencode-shell--render-messages
       (list user
             (opencode-shell-test--tool-message "a1" "u1")
             (opencode-shell-test--message "a2" "assistant" "answer" "u1")))
      (should (eq (opencode-shell--turn-status (car opencode-shell--turns)) 'complete))
      (should (equal (opencode-shell--turn-assistant (car opencode-shell--turns)) "answer")))))

(ert-deftest opencode-shell-composer-boundary-is-multiline-and-transcript-read-only ()
  (with-temp-buffer
    (opencode-shell-mode)
    (insert "first\nsecond")
    (should (equal (opencode-shell--composer-text) "first\nsecond"))
    (opencode-shell--render-messages
     (list (opencode-shell-test--message "u1" "user" "sent")
           (opencode-shell-test--message "a1" "assistant" "reply" "u1")))
    (let ((turn (car opencode-shell--turns)))
      (should (marker-position (opencode-shell--turn-user-begin turn)))
      (should (marker-position (opencode-shell--turn-user-end turn)))
      (should (marker-position (opencode-shell--turn-response-begin turn)))
      (should (marker-position (opencode-shell--turn-response-end turn)))
      (should (eq (get-text-property
                   (opencode-shell--turn-user-begin turn) 'read-only) t))
      (should (eq (get-text-property
                   (opencode-shell--turn-response-begin turn) 'read-only) t)))
    (should-error (let ((inhibit-read-only nil))
                     (goto-char (point-min)) (insert "x"))
                   :type 'text-read-only)
    (should-error (let ((inhibit-read-only nil))
                    (delete-region (1- opencode-shell--composer-start)
                                   (1+ opencode-shell--composer-start)))
                  :type 'text-read-only)
    (goto-char (point-max))
    (insert "\nthird")
    (should (equal (opencode-shell--composer-text) "first\nsecond\nthird"))))

(ert-deftest opencode-shell--submit-commits-clears-and-restores-on-failure ()
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--session-id "s"
          opencode-shell--selected-model '((providerID . "p") (modelID . "m"))
          opencode-shell--selected-agent "build")
    (insert "hello\nworld")
    (let (request failure)
      (cl-letf (((symbol-function 'opencode-shell--request)
                 (lambda (method path callback &optional body _params error-callback)
                   (setq request (list method path callback body)
                         failure error-callback))))
        (opencode-shell--submit)
        (should (equal (car request) "POST"))
        (should (equal (cadr request) "/session/s/prompt_async"))
        (should (equal (alist-get 'agent (nth 3 request)) "build"))
        (should (equal (alist-get 'model (nth 3 request)) opencode-shell--selected-model))
        (should (string-empty-p (opencode-shell--composer-text)))
        (should (equal (opencode-shell--turn-user (car opencode-shell--turns)) "hello\nworld"))
        (should (eq (get-text-property (point-min) 'read-only) t))
        (funcall failure)
        (should (equal (opencode-shell--composer-text) "hello\nworld"))
        (should (eq (opencode-shell--turn-status (car opencode-shell--turns)) 'error))
        (goto-char (point-min)) (search-forward "Request failed")
        (should (eq (get-text-property (match-beginning 0) 'face)
                    'opencode-shell-error-face))
        (should (equal opencode-shell--request-status "error"))))))

(ert-deftest opencode-shell-failure-does-not-overwrite-edited-composer ()
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--session-id "s")
    (insert "failed prompt")
    (let (failure)
      (cl-letf (((symbol-function 'opencode-shell--request)
                 (lambda (_method _path _callback &optional _body _params error-callback)
                   (setq failure error-callback))))
        (opencode-shell--submit)
        (insert "new draft")
        (goto-char (+ opencode-shell--composer-start 3))
        (funcall failure)
        (should (equal (opencode-shell--composer-text) "new draft"))
        (should (= (- (point) opencode-shell--composer-start) 3))))))

(ert-deftest opencode-shell-out-of-order-failures-do-not-restore-or-reorder-prompts ()
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--session-id "s")
    (let (failures)
      (cl-letf (((symbol-function 'opencode-shell--request)
                 (lambda (_method _path _callback &optional _body _params error-callback)
                   (setq failures (append failures (list error-callback))))))
        (insert "first")
        (opencode-shell--submit)
        (insert "second")
        (opencode-shell--submit)
        (funcall (car failures))
        (should (string-empty-p (opencode-shell--composer-text)))
        (funcall (cadr failures))
        (should (equal (opencode-shell--composer-text) "second"))
        (should (equal (mapcar #'opencode-shell--turn-user opencode-shell--turns)
                       '("first" "second")))))))

(ert-deftest opencode-shell-blank-submit-is-rejected-without-request ()
  (with-temp-buffer
    (opencode-shell-mode)
    (insert " \n ")
    (cl-letf (((symbol-function 'opencode-shell--request)
               (lambda (&rest _) (ert-fail "blank prompt requested"))))
      (should-error (opencode-shell--submit) :type 'user-error))
    (should (equal (opencode-shell--composer-text) " \n "))))

(ert-deftest opencode-shell-poll-insertion-preserves-composer-point-faces-and-id ()
  (with-temp-buffer
    (opencode-shell-mode)
    (insert "draft text")
    (goto-char (+ opencode-shell--composer-start 5))
    (let ((messages (list (opencode-shell-test--message "u1" "user" "question")
                          (opencode-shell-test--message "a1" "assistant" "answer" "u1"))))
      (opencode-shell--render-messages messages)
      (let ((id (opencode-shell--turn-id (car opencode-shell--turns))))
        (should (equal (opencode-shell--composer-text) "draft text"))
        (should (= (- (point) opencode-shell--composer-start) 5))
        (goto-char (point-min))
        (search-forward "ASSISTANT>")
        (let* ((turn (car opencode-shell--turns))
               (user-begin (opencode-shell--turn-user-begin turn))
               (user-end (opencode-shell--turn-user-end turn)))
          (opencode-shell--render-messages
           (list (opencode-shell-test--message "u1" "user" "question")
                 (opencode-shell-test--message "a1" "assistant" "updated" "u1")))
          (should (eq turn (car opencode-shell--turns)))
          (should (eq user-begin
                      (opencode-shell--turn-user-begin
                       (car opencode-shell--turns))))
          (should (eq user-end
                      (opencode-shell--turn-user-end
                       (car opencode-shell--turns)))))
        (opencode-shell--render-messages messages)
        (should (equal id (opencode-shell--turn-id (car opencode-shell--turns))))))))

(ert-deftest opencode-shell-waiting-face-model-agent-keys-and-header ()
  (should (eq (lookup-key opencode-shell-mode-map (kbd "C-c C-c")) #'opencode-shell--submit))
  (should (eq (lookup-key opencode-shell-mode-map (kbd "s-<return>")) #'opencode-shell--submit))
  (should (eq (lookup-key opencode-shell-mode-map (kbd "C-c C-v")) #'opencode-shell--select-model))
  (should (eq (lookup-key opencode-shell-mode-map (kbd "C-c C-m")) #'opencode-shell--select-agent))
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--directory "/work" opencode-shell--session-id "session"
          opencode-shell--models '(("p/m" . ((providerID . "p") (modelID . "m"))))
          opencode-shell--agents '(("build" . ((name . "build")))))
    (cl-letf (((symbol-function 'completing-read)
               (lambda (prompt &rest _) (if (string-prefix-p "Model" prompt) "p/m" "build"))))
      (opencode-shell--select-model)
      (opencode-shell--select-agent))
    (should (string-match-p "p/m.*build" (opencode-shell--header)))
    (setq opencode-shell--turns
          (list (opencode-shell--make-turn :id "local" :user "q" :status 'waiting)))
    (opencode-shell--render-turns)
    (goto-char (point-min)) (search-forward "Waiting")
    (should (eq (get-text-property (match-beginning 0) 'face)
                'opencode-shell-waiting-face))))

(ert-deftest opencode-shell-conversation-state-is-independent-between-buffers ()
  (let ((a (generate-new-buffer " *oc-turn-a*"))
        (b (generate-new-buffer " *oc-turn-b*")))
    (unwind-protect
        (progn
          (with-current-buffer a
            (opencode-shell-mode)
            (opencode-shell--render-messages
             (list (opencode-shell-test--message "same" "user" "one"))))
          (with-current-buffer b
            (opencode-shell-mode)
            (insert "two")
            (should-not opencode-shell--turns))
          (with-current-buffer a
            (should (= (length opencode-shell--turns) 1))
            (should (string-empty-p (opencode-shell--composer-text))))
          (with-current-buffer b (should (equal (opencode-shell--composer-text) "two"))))
      (kill-buffer a) (kill-buffer b))))

;; Profile and server lifecycle contract.  These tests intentionally use
;; complete profile plists: a profile is an immutable piece of configuration,
;; while resolved credentials and process ownership are transient state.

(defconst opencode-shell-test--local-profile
  '(:name "local" :base-url "http://127.0.0.1:7777/"
    :directory "/client/project" :workspace "/server/project"
    :start-command ("opencode" "serve") :server-directory "/tmp"
    :startup-timeout 2 :auth-source (:host "localhost" :port 7777)))

(defconst opencode-shell-test--remote-profile
  '(:name "remote" :base-url "https://code.example.test"
    :directory "/ssh:code.example.test:/srv/project"
    :workspace "/srv/project"
    :start-command ("opencode" "serve")))

(ert-deftest opencode-shell-profile-helpers-are-defined-before-public-commands ()
  (dolist (symbol '(opencode-shell--profile-key opencode-shell--profile-name
                    opencode-shell--default-profile opencode-shell--read-profile
                    opencode-shell--resolve-or-read-profile
                    opencode-shell--profile-remote-p))
    (should (fboundp symbol)))
  (should (boundp 'opencode-shell-profiles))
  (should (boundp 'opencode-shell--servers)))

(ert-deftest opencode-shell-default-local-endpoint-is-4199 ()
  (should (equal opencode-shell-base-url "http://127.0.0.1:4199")))

(ert-deftest opencode-shell-profile-key-name-default-and-read ()
  (let ((opencode-shell-profiles
         (list opencode-shell-test--local-profile
               opencode-shell-test--remote-profile))
        (default-directory "/client/project/src/") choice)
    (should (equal (opencode-shell--profile-name opencode-shell-test--local-profile)
                   "local"))
    (should (equal (opencode-shell--profile-key opencode-shell-test--local-profile)
                   (opencode-shell--profile-key (copy-tree opencode-shell-test--local-profile))))
    (should (equal (opencode-shell--default-profile)
                    (list :name "default" :base-url opencode-shell-base-url
                          :directory opencode-shell-directory)))
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_prompt candidates &rest _)
                 (setq choice candidates) "remote")))
      (should (equal (opencode-shell--read-profile)
                     opencode-shell-test--remote-profile))
      (let ((names (mapcar (lambda (item) (if (consp item) (car item) item)) choice)))
        (should (member "local" names))
        (should (member "remote" names))))))

(ert-deftest opencode-shell-profile-local-and-tramp-directory-mapping ()
  (should-not (opencode-shell--profile-remote-p opencode-shell-test--local-profile))
  (should (opencode-shell--profile-remote-p opencode-shell-test--remote-profile))
  (should (equal (opencode-shell--server-directory
                  "/client/project/src/a.el" opencode-shell-test--local-profile)
                 "/server/project/src/a.el"))
  (should (equal (opencode-shell--server-directory
                   "/ssh:code.example.test:/srv/project/src/a.el"
                   opencode-shell-test--remote-profile)
                  "/srv/project/src/a.el"))
  (should (equal (opencode-shell--server-directory
                  "/client/project/src/./lib/../a.el"
                  opencode-shell-test--local-profile)
                 "/server/project/src/a.el"))
  (should (equal (opencode-shell--server-directory
                  "/client/project/../outside/a.el"
                  opencode-shell-test--local-profile)
                 "/client/outside/a.el"))
  (should (equal (opencode-shell--server-directory
                  "/client/project-sibling/a.el"
                  opencode-shell-test--local-profile)
                 "/client/project-sibling/a.el"))
  (should (equal (opencode-shell--server-directory
                  "/ssh:code.example.test:/srv/project/src/../a.el"
                  opencode-shell-test--remote-profile)
                 "/srv/project/a.el"))
  (should (equal (opencode-shell--server-directory
                  "/ssh:code.example.test:/srv/project/../outside/a.el"
                  opencode-shell-test--remote-profile)
                 "/srv/outside/a.el"))
  (let ((broad '(:name "workspace" :directory "/Workspace"
                 :workspace "/server/Workspace")))
    (should (equal (opencode-shell--server-directory
                    "/Workspace/personal/translator/" broad)
                   "/server/Workspace/personal/translator/"))
    (should (equal (opencode-shell--server-directory "/Workspace/" broad)
                   "/server/Workspace/")))
  (let ((nested '(:name "nested" :directory "/work"
                  :workspace "/work/server")))
    (should (equal (opencode-shell--server-directory
                    "/work/server/project/" nested)
                   "/work/server/project/"))))

(ert-deftest opencode-shell-profile-scopes-url-directory-workspace-and-auth ()
  (let ((opencode-shell-auth-source-function
         (lambda (profile)
           (should (equal profile opencode-shell-test--local-profile))
           "Bearer profile-secret"))
        captured-url captured-headers messages)
    (with-temp-buffer
      (setq-local opencode-shell--profile opencode-shell-test--local-profile)
      (setq-local opencode-shell--directory "/server/project")
      (cl-letf (((symbol-function 'url-retrieve)
                 (lambda (url _callback &rest _)
                   (setq captured-url url captured-headers url-request-extra-headers)))
                ((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (push (apply #'format format-string args) messages))))
        (opencode-shell--request "GET" "/session" #'ignore)))
    (should (string-prefix-p "http://127.0.0.1:7777/session?" captured-url))
    (should (string-match-p "directory=%2Fserver%2Fproject" captured-url))
    (should (equal (cdr (assoc "Authorization" captured-headers))
                   "Bearer profile-secret"))
    (should-not (string-match-p "profile-secret"
                                (format "%S%S" opencode-shell-test--local-profile messages)))))

(ert-deftest opencode-shell-entry-opens-explicit-server-with-current-directory ()
  (let ((default-directory "/tmp/current/") opened)
    (cl-letf (((symbol-function 'opencode-shell--start-server)
               (lambda (profile callback) (funcall callback profile)))
              ((symbol-function 'opencode-shell--sessions)
                (lambda (&optional directory profile)
                  (setq opened (list directory profile)))))
      (opencode-shell opencode-shell-test--local-profile)
       (should (equal opened (list "/tmp/current/" opencode-shell-test--local-profile))))
    (let ((opencode-shell-poll-interval 60) buffers)
      (cl-letf (((symbol-function 'pop-to-buffer) (lambda (buffer &rest _) (push buffer buffers)))
                ((symbol-function 'opencode-shell--resync) #'ignore)
                ((symbol-function 'run-at-time) (lambda (&rest _) nil)))
        (unwind-protect
            (progn
              (opencode-shell-open-session "same-id" nil opencode-shell-test--local-profile)
              (opencode-shell-open-session "same-id" nil opencode-shell-test--remote-profile)
              (should (= (length (delete-dups buffers)) 2)))
          (mapc (lambda (buffer) (when (buffer-live-p buffer) (kill-buffer buffer))) buffers))))))

(ert-deftest opencode-shell-register-profile-commands-refreshes-and-isolates-profiles ()
  (let ((opencode-shell-profiles
         (list opencode-shell-test--local-profile opencode-shell-test--remote-profile))
        (opencode-shell--generated-profile-commands nil)
        opened)
    (unwind-protect
        (progn
          (opencode-shell--register-profile-commands)
          (should (commandp 'opencode-shell-local-sessions))
          (should (commandp 'opencode-shell-local-start))
          (should (commandp 'opencode-shell-remote-sessions))
          (should (commandp 'opencode-shell-remote-start))
          (cl-letf (((symbol-function 'opencode-shell--open-sessions)
                     (lambda (profile directory)
                       (push (list profile directory) opened))))
            (call-interactively 'opencode-shell-local-sessions)
            (call-interactively 'opencode-shell-remote-sessions))
          (should (equal (mapcar (lambda (entry)
                                   (cons (opencode-shell--profile-name (car entry))
                                         (cdr entry)))
                                 opened)
                         `(("remote" ,(expand-file-name default-directory))
                           ("local" ,(expand-file-name default-directory)))))
          (setq opencode-shell-profiles (list opencode-shell-test--local-profile))
          (opencode-shell--register-profile-commands)
          (should-not (fboundp 'opencode-shell-remote-sessions))
          (should-not (fboundp 'opencode-shell-remote-start)))
      (mapc (lambda (symbol) (when (fboundp symbol) (fmakunbound symbol)))
            opencode-shell--generated-profile-commands))))

(ert-deftest opencode-shell-register-profile-commands-rejects-invalid-and-colliding-names ()
  (let ((opencode-shell--generated-profile-commands nil))
    (let ((opencode-shell-profiles '((:name "bad/name" :base-url "http://localhost:1"))))
      (should-error (opencode-shell--register-profile-commands) :type 'user-error))
    (let ((opencode-shell-profiles
           '((:name "foo bar" :base-url "http://localhost:1")
             (:name "foo_bar" :base-url "http://localhost:2"))))
      (should-error (opencode-shell--register-profile-commands) :type 'user-error))))

(ert-deftest opencode-shell-register-profile-commands-does-not-overwrite-existing-functions ()
  (let ((opencode-shell-profiles
         '((:name "reserved" :base-url "http://localhost:1")))
        (opencode-shell--generated-profile-commands nil))
    (cl-letf (((symbol-function 'opencode-shell-reserved-sessions) #'ignore))
      (should-error (opencode-shell--register-profile-commands) :type 'user-error)
      (should (eq (symbol-function 'opencode-shell-reserved-sessions) #'ignore)))))

(ert-deftest opencode-shell-directory-scoped-launch-isolates-buffers ()
  (let* ((profile '(:name "workspace" :base-url "http://127.0.0.1:4096"
                      :directory "/Workspace" :workspace "/server/Workspace"))
         (default-directory "/Workspace/personal/translator/")
         requests buffers)
    (cl-letf (((symbol-function 'pop-to-buffer) (lambda (buffer &rest _) (push buffer buffers)))
              ((symbol-function 'opencode-shell--request)
               (lambda (method path _callback &optional _data query)
                 (push (list method path opencode-shell--directory query) requests))))
      (unwind-protect
          (progn
            (opencode-shell profile)
             (should (equal (cl-subseq (car requests) 0 3)
                            '("GET" "/session/status" "/server/Workspace/personal/translator/")))
            (opencode-shell--sessions "/Workspace/" profile)
             (should (equal (cl-subseq (car requests) 0 3)
                            '("GET" "/session/status" "/Workspace/")))
             (should (= (length (delete-dups buffers)) 2)))
        (mapc (lambda (buffer) (when (buffer-live-p buffer) (kill-buffer buffer))) buffers)))))

(ert-deftest opencode-shell--sessions-requires-and-stores-absolute-directory ()
  (let (seen)
    (cl-letf (((symbol-function 'pop-to-buffer) #'ignore)
              ((symbol-function 'opencode-shell--refresh)
               (lambda () (push (list opencode-shell--directory opencode-shell--profile) seen))))
      (unwind-protect
          (progn
             (opencode-shell--sessions "/legacy/directory" opencode-shell-test--remote-profile)
             (should (equal (car seen)
                            (list "/legacy/directory/" opencode-shell-test--remote-profile)))
             (should-error (opencode-shell--sessions "relative" opencode-shell-test--local-profile)
                           :type 'user-error))
        (mapc (lambda (buffer)
                (when (string-prefix-p "*OpenCode Shell Sessions:" (buffer-name buffer))
                  (kill-buffer buffer)))
              (buffer-list))))))

(ert-deftest opencode-shell-server-health-reuse-does-not-spawn ()
  (let ((opencode-shell--servers (make-hash-table :test #'equal)) spawned callback)
    (cl-letf (((symbol-function 'opencode-shell--server-ready)
               (lambda (profile ready) (funcall ready profile)))
              ((symbol-function 'make-process) (lambda (&rest _) (setq spawned t))))
      (opencode-shell--start-server opencode-shell-test--local-profile
                                    (lambda (profile) (setq callback profile))))
    (should-not spawned)
    (should (equal callback opencode-shell-test--local-profile))
    (let ((state (gethash (opencode-shell--server-key opencode-shell-test--local-profile)
                          opencode-shell--servers)))
      (should state)
      (should-not (plist-get state :owned))
      (should (plist-get state :config)))))

(ert-deftest opencode-shell-server-start-is-single-per-server-and-let-binds-directory ()
  (let ((opencode-shell--servers (make-hash-table :test #'equal))
        (make-calls 0) process-directory timers health-callback)
    (cl-letf (((symbol-function 'opencode-shell--server-ready)
               (lambda (_profile callback) (setq health-callback callback)))
              ((symbol-function 'make-process)
               (lambda (&rest _)
                 (cl-incf make-calls) (setq process-directory default-directory) 'fake-process))
              ((symbol-function 'process-live-p) (lambda (_) t))
              ((symbol-function 'run-at-time)
               (lambda (&rest args) (push args timers) 'fake-timer)))
      (opencode-shell--start-server opencode-shell-test--local-profile #'ignore)
      (opencode-shell--start-server opencode-shell-test--local-profile #'ignore)
      (funcall health-callback nil)
      (funcall health-callback nil))
    (should (= make-calls 1))
    (should (equal (directory-file-name process-directory) "/tmp"))
    (should timers)))

(ert-deftest opencode-shell-server-wait-is-bounded ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
          (key (opencode-shell--server-key opencode-shell-test--local-profile))
         scheduled messages)
    (puthash key (list :callbacks (list #'ignore) :starting t :attempt 'attempt)
             opencode-shell--servers)
    (cl-letf (((symbol-function 'float-time) (lambda (&optional _) 20.0))
              ((symbol-function 'run-at-time) (lambda (&rest args) (push args scheduled)))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (push (apply #'format format-string args) messages))))
      (opencode-shell--await-server opencode-shell-test--local-profile 10.0 'attempt))
    (should-not scheduled)
    (should-not (plist-get (gethash key opencode-shell--servers) :callbacks))
    (should (string-match-p "timed out" (car messages)))))

(ert-deftest opencode-shell-exited-child-adopts-healthy-endpoint ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (profile opencode-shell-test--local-profile)
         (key (opencode-shell--server-key profile))
         (process 'child) callback-profile)
    (puthash key (list :process process :owned t :starting t :attempt 'attempt
                       :callbacks (list (cons (lambda (value)
                                                (setq callback-profile value))
                                              profile)))
             opencode-shell--servers)
    (cl-letf (((symbol-function 'process-status) (lambda (_) 'exit))
              ((symbol-function 'process-exit-status) (lambda (_) 1))
              ((symbol-function 'process-buffer) (lambda (_) nil))
              ((symbol-function 'opencode-shell--server-ready)
               (lambda (_profile callback) (funcall callback t))))
      (opencode-shell--process-sentinel key 'attempt process "exited")
      (should (gethash key opencode-shell--servers))
      (opencode-shell--await-server profile (+ (float-time) 1) 'attempt))
    (should (equal callback-profile profile))
    (let ((state (gethash key opencode-shell--servers)))
      (should state)
      (should-not (plist-get state :owned))
      (should-not (plist-get state :starting)))))

(ert-deftest opencode-shell-exited-child-unhealthy-reports-output-tail ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (profile opencode-shell-test--local-profile)
         (key (opencode-shell--server-key profile))
         (process 'child)
         (buffer (generate-new-buffer " *oc-exit-tail*")) messages)
    (unwind-protect
        (progn
          (with-current-buffer buffer (insert "address already in use"))
          (puthash key (list :process process :owned t :starting t :attempt 'attempt)
                   opencode-shell--servers)
          (cl-letf (((symbol-function 'process-status) (lambda (_) 'exit))
                    ((symbol-function 'process-exit-status) (lambda (_) 1))
                    ((symbol-function 'process-buffer) (lambda (_) buffer))
                    ((symbol-function 'float-time) (lambda (&optional _) 20.0))
                    ((symbol-function 'message)
                     (lambda (format-string &rest args)
                       (push (apply #'format format-string args) messages))))
            (opencode-shell--process-sentinel key 'attempt process "exited")
            (should (gethash key opencode-shell--servers))
            (opencode-shell--await-server profile 10.0 'attempt))
          (should-not (gethash key opencode-shell--servers))
          (should (string-match-p "status 1" (car messages)))
          (should (string-match-p "address already in use" (car messages))))
      (kill-buffer buffer))))

(ert-deftest opencode-shell-explicit-stop-restart-and-owned-only-stop ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (profile opencode-shell-test--local-profile)
          (key (opencode-shell--server-key profile)) deleted started)
    (puthash key (list :process 'owned :owned t) opencode-shell--servers)
    (cl-letf (((symbol-function 'process-live-p) (lambda (process) (eq process 'owned)))
              ((symbol-function 'delete-process) (lambda (process) (setq deleted process))))
      (opencode-shell--stop-server profile))
    (should (eq deleted 'owned))
    (should-not (gethash key opencode-shell--servers))
    (puthash key (list :process 'foreign :owned nil) opencode-shell--servers)
    (should-error (opencode-shell--stop-server profile) :type 'user-error)
    (puthash key (list :process 'owned :owned t) opencode-shell--servers)
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) t))
              ((symbol-function 'delete-process) #'ignore)
              ((symbol-function 'opencode-shell--start-server)
               (lambda (value &rest _) (setq started value))))
      (opencode-shell--restart-server profile))
    (should (equal started profile))))

(ert-deftest opencode-shell-remote-profile-never-autostarts ()
  (let ((opencode-shell--servers (make-hash-table :test #'equal)) spawned)
    (cl-letf (((symbol-function 'make-process) (lambda (&rest _) (setq spawned t))))
      (opencode-shell--start-server opencode-shell-test--remote-profile #'ignore))
    (should-not spawned)
    (should (= (hash-table-count opencode-shell--servers) 0))))

(ert-deftest opencode-shell-killing-transcript-does-not-stop-owned-server ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (profile opencode-shell-test--local-profile)
          (key (opencode-shell--server-key profile)) stopped)
    (puthash key (list :process 'owned :owned t) opencode-shell--servers)
    (with-temp-buffer
      (opencode-shell-mode)
      (setq-local opencode-shell--profile profile)
      (cl-letf (((symbol-function 'delete-process) (lambda (&rest _) (setq stopped t))))
        (opencode-shell--cleanup)))
    (should-not stopped)
    (should (gethash key opencode-shell--servers))))

(ert-deftest opencode-shell-health-probe-is-async-and-coalesced ()
  (let ((opencode-shell--servers (make-hash-table :test #'equal)) probe (spawned 0))
    (cl-letf (((symbol-function 'opencode-shell--server-ready)
               (lambda (_profile callback) (setq probe callback)))
               ((symbol-function 'opencode-shell--spawn-server)
                (lambda (_profile _attempt) (cl-incf spawned))))
      (opencode-shell--start-server opencode-shell-test--local-profile #'ignore)
      (opencode-shell--start-server opencode-shell-test--local-profile #'ignore)
      (should (= spawned 0))
      (funcall probe nil)
      (should (= spawned 1)))))

(ert-deftest opencode-shell-shared-server-healthy-reuse-is-profile-isolated ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (one opencode-shell-test--local-profile)
         (two (plist-put (copy-tree one) :name "other"))
         (profiles nil) (probes 0) spawned)
    (cl-letf (((symbol-function 'opencode-shell--server-ready)
               (lambda (_profile callback)
                 (cl-incf probes) (funcall callback t)))
              ((symbol-function 'make-process)
               (lambda (&rest _) (setq spawned t))))
      (opencode-shell--start-server one (lambda (profile) (push profile profiles)))
      (opencode-shell--start-server two (lambda (profile) (push profile profiles))))
    (should (= probes 2))
    (should-not spawned)
    (should (equal profiles (list two one)))))

(ert-deftest opencode-shell-shared-server-coalesces-spawn-and-callbacks ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (one opencode-shell-test--local-profile)
         (two (plist-put (copy-tree one) :name "other"))
         probe (spawns 0) profiles)
    (cl-letf (((symbol-function 'opencode-shell--server-ready)
               (lambda (_profile callback) (setq probe callback)))
               ((symbol-function 'opencode-shell--spawn-server)
                (lambda (profile attempt)
                  (cl-incf spawns)
                  (opencode-shell--finish-start
                   (opencode-shell--server-key profile) attempt))))
      (opencode-shell--start-server one (lambda (profile) (push profile profiles)))
      (opencode-shell--start-server two (lambda (profile) (push profile profiles)))
      (funcall probe nil))
    (should (= spawns 1))
    (should (equal profiles (list two one)))))

(ert-deftest opencode-shell-shared-server-rejects-conflicting-config ()
  (let* ((one opencode-shell-test--local-profile)
         (two (plist-put (copy-tree one) :name "other"))
         (two (plist-put two :health-path "/ready"))
         (opencode-shell-profiles (list one two)))
    (should-error (opencode-shell--validate-profiles) :type 'user-error))
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (one opencode-shell-test--local-profile)
         (two (plist-put (copy-tree one) :startup-timeout 99)))
    (puthash (opencode-shell--server-key one)
             (list :config (opencode-shell--server-lifecycle-config one))
             opencode-shell--servers)
    (should-error (opencode-shell--start-server two) :type 'user-error)))

(ert-deftest opencode-shell-shared-auth-selectors-use-effective-values ()
  (let* ((one '(:name "one" :base-url "http://localhost:80/"
                :start-command ("serve") :auth-host "auth.test"
                :auth-port 443 :auth-user "user"))
         (two '(:name "two" :base-url "http://127.0.0.1"
                :start-command ("serve")
                :auth-source (:host "auth.test" :port 443 :user "user")
                :auth-header "Authorization"))
         (opencode-shell-profiles (list one two)))
    (should (equal (opencode-shell--server-key one)
                   (opencode-shell--server-key two)))
    (should (equal (opencode-shell--server-lifecycle-config one)
                   (opencode-shell--server-lifecycle-config two)))
    (opencode-shell--validate-profiles))
  (let* ((one '(:base-url "http://localhost" :start-command ("serve")
                :auth-host "one.test"))
         (two '(:base-url "http://localhost:80" :start-command ("serve")
                :auth-source (:host "two.test"))))
    (should-error
     (opencode-shell--validate-server-profile
      two (list :config (opencode-shell--server-lifecycle-config one)))
     :type 'user-error)))

(ert-deftest opencode-shell-server-key-canonicalizes-safe-equivalents ()
  (dolist (urls '(("http://localhost" "http://127.0.0.1:80/")
                  ("https://localhost" "https://[::1]:443/")))
    (should (equal (opencode-shell--server-key (list :base-url (car urls)))
                   (opencode-shell--server-key (list :base-url (cadr urls))))))
  (should-not (equal (opencode-shell--server-key '(:base-url "http://localhost"))
                     (opencode-shell--server-key '(:base-url "https://localhost"))))
  (should-not (equal (opencode-shell--server-key '(:base-url "http://localhost"))
                     (opencode-shell--server-key '(:base-url "http://localhost:81")))))

(ert-deftest opencode-shell-owned-live-server-survives-failed-health-probe ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (profile opencode-shell-test--local-profile)
         (key (opencode-shell--server-key profile)) callback spawned)
    (puthash key (list :process 'owned :owned t
                       :config (opencode-shell--server-lifecycle-config profile))
             opencode-shell--servers)
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) t))
              ((symbol-function 'opencode-shell--server-ready)
               (lambda (_profile ready) (funcall ready nil)))
              ((symbol-function 'make-process) (lambda (&rest _) (setq spawned t))))
      (opencode-shell--start-server profile (lambda (value) (setq callback value))))
    (let ((state (gethash key opencode-shell--servers)))
      (should-not spawned)
      (should (eq (plist-get state :process) 'owned))
      (should (plist-get state :owned))
      (should (equal callback profile)))))

(ert-deftest opencode-shell-stale-start-callback-cannot-mutate-new-attempt ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (profile opencode-shell-test--local-profile)
         (key (opencode-shell--server-key profile)) probes callbacks spawned)
    (cl-letf (((symbol-function 'opencode-shell--server-ready)
               (lambda (_profile callback) (push callback probes)))
              ((symbol-function 'opencode-shell--spawn-server)
               (lambda (_profile _attempt) (setq spawned t))))
      (opencode-shell--start-server profile (lambda (_) (push 'old callbacks)))
      (let ((old-probe (car probes)))
        (remhash key opencode-shell--servers)
        (opencode-shell--start-server profile (lambda (_) (push 'new callbacks)))
        (let ((new-state (gethash key opencode-shell--servers)))
          (funcall old-probe nil)
          (should-not spawned)
          (should (eq new-state (gethash key opencode-shell--servers)))
          (funcall (car probes) t))))
    (should (equal callbacks '(new)))))

(ert-deftest opencode-shell-shared-stop-restart-and-distinct-independence ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (one opencode-shell-test--local-profile)
         (two (plist-put (copy-tree one) :name "other"))
         (distinct (plist-put (copy-tree one) :base-url "http://127.0.0.1:8888"))
         (key (opencode-shell--server-key one)) deleted started)
    (should-not (equal key (opencode-shell--server-key distinct)))
    (puthash key (list :process 'owned :owned t) opencode-shell--servers)
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) t))
              ((symbol-function 'delete-process) (lambda (process) (setq deleted process))))
      (opencode-shell--stop-server two))
    (should (eq deleted 'owned))
    (puthash key (list :process 'owned :owned t) opencode-shell--servers)
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) t))
              ((symbol-function 'delete-process) #'ignore)
              ((symbol-function 'opencode-shell--start-server)
               (lambda (profile &rest _) (setq started profile))))
      (opencode-shell--restart-server two))
    (should (equal started two))))

(ert-deftest opencode-shell-browser-state-is-buffer-and-generation-isolated ()
  (let ((one (generate-new-buffer " *oc-one*"))
        (two (generate-new-buffer " *oc-two*")) requests)
    (unwind-protect
        (cl-letf (((symbol-function 'opencode-shell--request)
                   (lambda (_method path callback &rest _)
                     (push (list (current-buffer) path callback) requests))))
          (dolist (buffer (list one two))
            (with-current-buffer buffer
              (opencode-shell-sessions-mode)
              (opencode-shell--refresh)))
          (dolist (request (copy-sequence requests))
            (when (equal (cadr request) "/session/status")
              (with-current-buffer (car request)
                (funcall (nth 2 request)
                         `((,(if (eq (car request) one) "one" "two")
                            . ((type . "busy"))))))))
          (dolist (request requests)
            (when (equal (cadr request) "/session")
              (with-current-buffer (car request)
                (funcall (nth 2 request)
                         `(((id . ,(if (eq (car request) one) "one" "two"))))))))
          (should (equal (with-current-buffer one (opencode-shell--get
                                                   opencode-shell--session-status "one"))
                         '((type . "busy"))))
          (should (equal (with-current-buffer one
                           (opencode-shell--get (car opencode-shell--sessions) 'id)) "one"))
          (should (equal (with-current-buffer two
                           (opencode-shell--get (car opencode-shell--sessions) 'id)) "two")))
      (kill-buffer one) (kill-buffer two))))

(ert-deftest opencode-shell-profile-validation-rejects-duplicate-identities ()
  (let ((opencode-shell-profiles
         '((:name "duplicate" :id "one") (:name "duplicate" :id "two"))))
    (should-error (opencode-shell--validate-profiles) :type 'user-error))
  (let ((opencode-shell-profiles
         '((:name "one" :id "same") (:name "two" :id "same"))))
    (should-error (opencode-shell--validate-profiles) :type 'user-error)))

(ert-deftest opencode-shell-browser-has-fixed-directory-and-no-project-column ()
  (with-temp-buffer
    (opencode-shell-sessions-mode)
    (setq-local opencode-shell--directory "/home/server"
                opencode-shell--sessions
                '(((id . "one") (title . "Same") (directory . "/work/one"))
                  ((id . "two") (title . "Same") (directory . "/work/two"))))
    (setq tabulated-list-entries (opencode-shell--session-entries))
    (should (equal (mapcar #'car tabulated-list-entries) '("one" "two")))
    (should (equal opencode-shell--directory "/home/server"))
    (should-not (assoc "Project" (append tabulated-list-format nil)))))

(ert-deftest opencode-shell-opened-session-keeps-row-directory-for-follow-up-requests ()
  (let ((profile opencode-shell-test--remote-profile)
        (opencode-shell-poll-interval 60) browser transcript requests)
    (cl-letf (((symbol-function 'pop-to-buffer)
               (lambda (buffer &rest _) (setq transcript buffer)))
              ((symbol-function 'run-at-time) (lambda (&rest _) nil))
              ((symbol-function 'opencode-shell--request)
               (lambda (_method path callback &rest _)
                 (push (list path opencode-shell--directory) requests)
                 (when (member path '("/session/s/message" "/permission" "/question"))
                   (funcall callback nil)))))
      (unwind-protect
          (progn
            (setq browser (generate-new-buffer " *oc-browser-directory*"))
            (with-current-buffer browser
              (opencode-shell-sessions-mode)
              (setq-local opencode-shell--profile profile
                          opencode-shell--directory "/home/remote"
                          opencode-shell--sessions
                          '(((id . "s") (directory . "/srv/other"))))
              (let ((inhibit-read-only t))
                (insert (propertize "s" 'tabulated-list-id "s")))
              (goto-char (point-min))
              (opencode-shell--open-at-point))
            (with-current-buffer transcript
              (opencode-shell--abort)
              (should-error (opencode-shell--permissions) :type 'user-error)
              (should-error (opencode-shell--questions) :type 'user-error))
            (should requests)
            (dolist (request requests)
              (should (equal (cadr request) "/srv/other"))))
        (when (buffer-live-p browser) (kill-buffer browser))
        (when (buffer-live-p transcript) (kill-buffer transcript))))))

(ert-deftest opencode-shell-custom-raw-auth-header-covers-health ()
  (let ((profile '(:name "auth" :base-url "http://localhost:9"
                   :auth-header "X-OpenCode-Token"))
        (opencode-shell-auth-source-function (lambda (_) "raw-secret")) headers)
    (cl-letf (((symbol-function 'url-retrieve)
               (lambda (_url _callback &rest _)
                 (setq headers url-request-extra-headers))))
      (opencode-shell--server-ready profile #'ignore))
    (should (equal (cdr (assoc "X-OpenCode-Token" headers)) "raw-secret"))
    (should-not (string-match-p "Bearer" (format "%S" headers)))))

(ert-deftest opencode-shell-process-tail-and-package-exit-cleanup ()
  (let ((buffer (generate-new-buffer " *oc-tail*")) deleted
        (opencode-shell--servers (make-hash-table :test #'equal)))
    (unwind-protect
        (cl-letf (((symbol-function 'process-buffer) (lambda (_) buffer))
                  ((symbol-function 'process-live-p) (lambda (_) t))
                  ((symbol-function 'delete-process) (lambda (p) (push p deleted))))
          (opencode-shell--process-filter 'process (make-string 5000 ?x))
          (should (<= (with-current-buffer buffer (buffer-size))
                      opencode-shell--process-tail-limit))
          (puthash "one" '(:process owned :owned t
                           :config (:stop-on-exit t)) opencode-shell--servers)
          (puthash "two" '(:process foreign :owned nil) opencode-shell--servers)
          (opencode-shell--stop-all-servers)
          (should (equal deleted '(owned)))
          (should (= (hash-table-count opencode-shell--servers) 0)))
      (kill-buffer buffer))))

(ert-deftest opencode-shell-make-process-error-clears-start-state ()
  (let ((opencode-shell--servers (make-hash-table :test #'equal)) messages)
    (cl-letf (((symbol-function 'make-process) (lambda (&rest _) (error "spawn failed")))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (push (apply #'format format-string args) messages))))
      (puthash (opencode-shell--server-key opencode-shell-test--local-profile)
               '(:starting t :attempt attempt :callbacks (ignore)) opencode-shell--servers)
      (opencode-shell--spawn-server opencode-shell-test--local-profile 'attempt))
    (should (= (hash-table-count opencode-shell--servers) 0))
    (should (string-match-p "could not start server" (car messages)))))

(provide 'opencode-shell-test)
;;; opencode-shell-test.el ends here
