;;; opencode-shell-recovery-test.el --- Bounded retry tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'opencode-shell-recovery)
(require 'opencode-shell-async)

(ert-deftest opencode-shell-recovery-bounds-retries-after-five-failures ()
  (let ((opencode-shell-recovery--states (make-hash-table :test #'equal))
        timers delays (wakes 0))
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (delay _repeat callback &rest args)
                 (push delay delays)
                 (let ((timer (list 'timer callback args)))
                   (push timer timers)
                   timer)))
              ((symbol-function 'timerp)
               (lambda (value) (eq (car-safe value) 'timer)))
              ((symbol-function 'cancel-timer) #'ignore))
      (dotimes (index 5)
        (opencode-shell-recovery-failed
         'remote (lambda () (cl-incf wakes)) (lambda () t))
        (when (< index 4)
          (let ((timer (car timers)))
            (apply (nth 1 timer) (nth 2 timer)))))
      (should (equal (nreverse delays) '(1 2 4 8)))
      (should (opencode-shell-recovery-exhausted-p 'remote))
      (opencode-shell-recovery-failed 'remote #'ignore (lambda () t))
      (should (= (length timers) 4))
      (should (= wakes 4))
      (opencode-shell-recovery-manual-reset 'remote)
      (should-not (opencode-shell-recovery-exhausted-p 'remote))
      (opencode-shell-recovery-failed 'remote #'ignore (lambda () t))
      (should (equal (car delays) 1))
      (opencode-shell-recovery-success 'remote)
      (should-not (opencode-shell-recovery-offline-p 'remote)))))

(ert-deftest opencode-shell-recovery-attempt-deadline-ignores-stale-callback ()
  (let ((opencode-shell-recovery--states (make-hash-table :test #'equal))
        timers cancelled (expired 0))
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (_delay _repeat callback &rest args)
                 (let ((timer (list 'timer callback args)))
                   (push timer timers)
                   timer)))
              ((symbol-function 'timerp)
               (lambda (value) (eq (car-safe value) 'timer)))
              ((symbol-function 'cancel-timer)
               (lambda (timer) (push timer cancelled))))
      (opencode-shell-recovery-watch-attempt 'remote (lambda () (cl-incf expired)))
      (let ((old (car timers)))
        (opencode-shell-recovery-watch-attempt 'remote (lambda () (cl-incf expired)))
        (should (memq old cancelled))
        (apply (nth 1 old) (nth 2 old))
        (should (= expired 0))
        (let ((current (car timers)))
          (apply (nth 1 current) (nth 2 current))
          (apply (nth 1 current) (nth 2 current))
          (should (= expired 1)))))))

(ert-deftest opencode-shell-recovery-no-demand-cancels-pending-retry ()
  (let ((opencode-shell-recovery--states (make-hash-table :test #'equal))
        timer woke)
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (_delay _repeat callback &rest args)
                 (setq timer (cons callback args))
                 nil)))
      (opencode-shell-recovery-failed 'remote (lambda () (setq woke t))
                                      (lambda () nil))
      (apply (car timer) (cdr timer))
      (should-not woke)
      (should-not (gethash 'remote opencode-shell-recovery--states)))))

(ert-deftest opencode-shell-recovery-pauses-existing-poll-cadence ()
  (let ((opencode-shell-async--runtimes (make-hash-table :test #'equal))
        (buffer (generate-new-buffer " *offline-poll-test*"))
        scheduled cancelled wakes)
    (unwind-protect
        (cl-letf (((symbol-function 'run-at-time)
                   (lambda (&rest args)
                     (let ((timer (list 'timer args)))
                       (push timer scheduled) timer)))
                  ((symbol-function 'timerp)
                   (lambda (item) (eq (car-safe item) 'timer)))
                  ((symbol-function 'cancel-timer)
                   (lambda (timer) (push timer cancelled)))
                  ((symbol-function 'opencode-shell-async--deliver-runtime)
                   (lambda (&rest _) (push t wakes))))
          (opencode-shell-async-subscribe-runtime
           'ssh buffer "http://example.test/event" nil nil 2 #'ignore)
          (let ((initial (car scheduled)))
            (opencode-shell-async-pause-runtime 'ssh)
            (should (member initial cancelled))
            (opencode-shell-async--poll-runtime 'ssh)
            (should-not wakes)
            (opencode-shell-async-resume-runtime 'ssh)
            (should (= (length scheduled) 2))
            (opencode-shell-async--poll-runtime 'ssh)
            (should wakes)))
      (kill-buffer buffer))))

(provide 'opencode-shell-recovery-test)
;;; opencode-shell-recovery-test.el ends here
