;;; opencode-shell-test.el --- Tests for opencode-shell -*- lexical-binding: t; -*-

;; Copyright (C) 2026
;; Author: opencode-shell contributors
;; Package-Requires: ((emacs "27.1"))

;;; Code:

(require 'ert)
(require 'opencode-shell)

(ert-deftest opencode-shell-query-and-payload ()
  (should (equal (opencode-shell--query '((directory . "/tmp/a b") (empty)))
                 "directory=%2Ftmp%2Fa%20b"))
  (with-temp-buffer
    (setq-local opencode-shell--selected-model
                '((providerID . "openai") (modelID . "gpt")))
    (setq-local opencode-shell--selected-agent "build")
    (let ((body (opencode-shell--prompt-body "안녕")))
      (should (equal (alist-get 'agent body) "build"))
      (should (equal (alist-get 'model body) opencode-shell--selected-model))
      (should (equal (alist-get 'text (aref (alist-get 'parts body) 0)) "안녕")))))

(ert-deftest opencode-shell-session-normalization-and-filter ()
  (let* ((old '((id . "old") (title . "Alpha") (time (updated . 1000))))
         (new '((id . "new") (title . "Beta") (directory . "/work")
                (time (updated . 3000)))))
    (with-temp-buffer
      (setq-local opencode-shell--sessions
                  (opencode-shell--normalize-sessions (list old new old)))
      (should (equal (mapcar (lambda (x) (opencode-shell--get x 'id))
                             opencode-shell--sessions) '("new" "old")))
      (setq-local opencode-shell--filter "work")
      (should (equal (mapcar #'car (opencode-shell--session-entries)) '("new"))))))

(ert-deftest opencode-shell-open-at-point-forwards-explicit-directory ()
  (with-temp-buffer
    (insert (propertize "one" 'tabulated-list-id "s1"))
    (goto-char (point-min))
    (setq-local opencode-shell--directory "/scope/exact")
    (let (opened)
      (cl-letf (((symbol-function 'opencode-shell-open-session)
                 (lambda (id directory) (setq opened (list id directory)))))
        (opencode-shell-open-at-point)
        (should (equal opened '("s1" "/scope/exact")))))))

(ert-deftest opencode-shell-create-session-captures-explicit-directory ()
  (with-temp-buffer
    (setq-local opencode-shell--directory "/scope/origin")
    (let (callback opened)
      (cl-letf (((symbol-function 'opencode-shell--request)
                 (lambda (_method _path cb &rest _) (setq callback cb)))
                ((symbol-function 'opencode-shell-open-session)
                 (lambda (id directory) (setq opened (list id directory)))))
        (opencode-shell-create-session "New")
        (setq-local opencode-shell--directory "/scope/changed")
        (funcall callback '((id . "created")))
        (should (equal opened '("created" "/scope/origin")))))))

(ert-deftest opencode-shell-model-agent-normalization ()
  (let* ((models (opencode-shell--normalize-models
                  '((all . (((id . "p") (models . (("m" . ((id . "m")))))))))))
         (agents (opencode-shell--normalize-agents
                  '(((name . "build")) ((name . "plan"))))))
    (should (equal (caar models) "p/m"))
    (should (equal (mapcar #'car agents) '("build" "plan")))
    (should (equal (opencode-shell--preserve-choice
                    '((providerID . "p") (modelID . "m")) models)
                   '((providerID . "p") (modelID . "m"))))))

(ert-deftest opencode-shell-model-object-and-session-display ()
  (let ((models (opencode-shell--normalize-models
                 '((all . (((id . "p")
                            (models . (((id . "one"))
                                       ("two" . ((name . "Two"))))))))))))
    (should (equal (mapcar #'car models) '("p/one" "p/two")))
    (should (equal (mapcar #'car
                           (opencode-shell--normalize-models
                            '((providers . (((id . "q")
                                             (models . ((three . ((name . "Three")))))))))))
                   '("q/three")))
    (should (equal (aref (cadr (opencode-shell--session-row
                                '((id . "s") (model . ((providerID . "p")
                                                       (modelID . "one")))))) 4)
                   "p/one"))
    (should (equal (aref (cadr (opencode-shell--session-row
                                '((id . "s") (model . "p/two")))) 4)
                   "p/two"))))

(ert-deftest opencode-shell-http-status-and-bounded-errors ()
  (should (<= (string-width (opencode-shell--bounded-error
                             (concat "bad\n" (make-string 500 ?x)))) 300))
  (let (called messages)
    (cl-letf (((symbol-function 'url-retrieve)
               (lambda (_ callback &rest _)
                 (with-temp-buffer
                   (insert "HTTP/1.1 204 No Content\r\n\r\n")
                   (setq-local url-http-response-status 204)
                   (funcall callback nil))))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (push (apply #'format format-string args) messages))))
      (opencode-shell--request "GET" "/ok" (lambda (value) (setq called (list value))))
      (should (equal called '(nil)))
      (setq called nil)
      (cl-letf (((symbol-function 'url-retrieve)
                 (lambda (_ callback &rest _)
                   (with-temp-buffer
                     (insert "HTTP/1.1 300 Multiple\r\n\r\nnot success")
                     (setq-local url-http-response-status 300)
                     (funcall callback nil)))))
        (opencode-shell--request "GET" "/bad" (lambda (_) (setq called t))))
      (should-not called)
      (should (string-match-p "HTTP 300: not success" (car messages))))))

(ert-deftest opencode-shell-question-multiple-custom-semantics ()
  (let ((item '((id . "q")
                (questions . (((question . "Single choice")
                               (options . (((label . "A")) ((label . "B")))))
                              ((question . "Single custom") (custom . t)
                               (options . (((label . "C")))))
                              ((question . "Multiple choice") (multiple . t)
                               (options . (((label . "D")) ((label . "E")))))
                              ((question . "Multiple custom") (multiple . t)
                               (custom . t) (options . (((label . "F")))))))))
        requests completion-calls)
    (cl-letf (((symbol-function 'opencode-shell--choose-pending)
               (lambda (_ callback) (funcall callback item)))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
              ((symbol-function 'completing-read)
               (lambda (prompt collection _predicate require-match &rest _)
                 (push (list 'single prompt collection require-match)
                       completion-calls)
                 (if require-match "B" "own single")))
              ((symbol-function 'completing-read-multiple)
               (lambda (prompt collection _predicate require-match &rest _)
                 (push (list 'multiple prompt collection require-match)
                       completion-calls)
                 (if require-match '("E" "D") '("own first" "F" "own last"))))
              ((symbol-function 'opencode-shell--request)
               (lambda (method path _callback &optional body &rest _)
                 (push (list method path body) requests))))
      (opencode-shell-questions)
      (should (equal (caddar requests)
                     '((answers . [["B"] ["own single"] ["E" "D"]
                                   ["own first" "F" "own last"]]))))
      (should (equal (json-serialize (caddar requests))
                     "{\"answers\":[[\"B\"],[\"own single\"],[\"E\",\"D\"],[\"own first\",\"F\",\"own last\"]]}"))
      (should
       (equal (nreverse completion-calls)
              '((single "Single choice [A, B]: " ("A" "B") t)
                (single "Single custom [C]: " ("C") nil)
                (multiple "Multiple choice [D, E]: " ("D" "E") t)
                (multiple "Multiple custom [F]: " ("F") nil)))))))

(ert-deftest opencode-shell-question-rejection ()
  (let ((item '((id . "q") (question . "Question"))) requests)
    (cl-letf (((symbol-function 'opencode-shell--choose-pending)
               (lambda (_ callback) (funcall callback item)))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) nil))
              ((symbol-function 'opencode-shell--request)
               (lambda (method path _callback &optional body &rest _)
                 (push (list method path body) requests))))
      (opencode-shell-questions)
      (should (equal (cadar requests) "/question/q/reject")))))

(ert-deftest opencode-shell-permission-replies-and-presentation ()
  (let ((item '((id . "p1") (permission . "bash")
                (patterns . ("git status" "git diff"))
                (always . ("git *"))
                (tool . ((name . "shell") (command . "git status")))
                (metadata . ((cwd . "/work") (reason . "inspect")))))
        requests choice prompt confirmations)
    (cl-letf (((symbol-function 'opencode-shell--choose-pending)
               (lambda (_kind callback) (funcall callback item)))
              ((symbol-function 'completing-read)
               (lambda (shown candidates &rest _)
                 (setq prompt shown)
                 (should (equal (mapcar #'car candidates)
                                '("Allow once" "Always allow" "Reject")))
                 choice))
              ((symbol-function 'yes-or-no-p)
               (lambda (shown) (push shown confirmations) t))
              ((symbol-function 'opencode-shell--request)
               (lambda (method path _callback &optional body &rest _)
                 (push (list method path body) requests))))
      (setq choice "Allow once")
      (opencode-shell-permissions)
      (should (equal (car requests)
                     '("POST" "/permission/p1/reply" ((reply . "once")))))
      (should (string-match-p "bash.*git status.*git diff" prompt))
      (should (string-match-p "always=.*git \\*" prompt))
      (should (string-match-p "tool=.*shell" prompt))
      (should (string-match-p "metadata=.*cwd.*work" prompt))
      (should-not confirmations)

      (setq choice "Reject" requests nil)
      (opencode-shell-permissions)
      (should (equal (caddar requests) '((reply . "reject"))))
      (should-not confirmations)

      (setq choice "Always allow" requests nil)
      (opencode-shell-permissions)
      (should (equal (caddar requests) '((reply . "always"))))
      (should (string-match-p "WARNING: Always allow persists" (car confirmations)))
      (should (string-match-p "metadata=.*cwd.*work" (car confirmations)))

      (setq requests nil confirmations nil)
      (cl-letf (((symbol-function 'yes-or-no-p)
                 (lambda (shown) (push shown confirmations) nil)))
        (opencode-shell-permissions))
      (should confirmations)
      (should-not requests))))

(ert-deftest opencode-shell-permission-pending-label-shows-patterns ()
  (let (candidates)
    (cl-letf (((symbol-function 'opencode-shell--request)
               (lambda (_method _path callback &rest _)
                 (funcall callback
                          '(((id . "p2") (permission . "edit")
                             (patterns . ("src/a.el" "src/b.el")))))))
              ((symbol-function 'completing-read)
               (lambda (_prompt table &rest _)
                 (setq candidates (mapcar #'car table))
                 (caar table))))
      (opencode-shell--choose-pending "permission" #'ignore)
      (should (string-match-p
               "p2: edit.*patterns=.*src/a.el.*src/b.el" (car candidates))))))

(ert-deftest opencode-shell-permission-context-is-bounded ()
  (let ((description
         (opencode-shell--permission-description
          `((permission . "read")
            (metadata . ((payload . ,(make-string 1000 ?x))))))))
    (should (< (length description) 250))
    (should (string-match-p "metadata=" description))))

(ert-deftest opencode-shell-polling-generation-and-capabilities ()
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--session-id "s" opencode-shell--generation 1)
    (let (requests stale)
      (cl-letf (((symbol-function 'opencode-shell--request)
                 (lambda (_ path callback &optional _body _params error-callback)
                   (push (list path callback error-callback) requests))))
        (opencode-shell-resync)
        (should (= (length requests) 3))
        (should opencode-shell--capabilities-loading)
        (should-not opencode-shell--capabilities-loaded)
        ;; A poll while the capability pair is pending must not overlap it.
        (opencode-shell-resync)
        (should (= (length requests) 3))
        (funcall (cadr (assoc "/provider" requests)) '((providers . nil)))
        (should-not opencode-shell--capabilities-loaded)
        (funcall (cadr (assoc "/agent" requests)) nil)
        (should opencode-shell--capabilities-loaded)
        (should-not opencode-shell--capabilities-loading)
        (let ((old (cadr (assoc "/session/s/message" requests))))
          (setq opencode-shell--generation 2
                opencode-shell--in-flight '((messages . t)) requests nil)
          (cl-letf (((symbol-function 'opencode-shell--render-messages)
                     (lambda (_) (setq stale t))))
            (funcall old nil))
          (should-not stale)
          (should (alist-get 'messages opencode-shell--in-flight))
          (setq opencode-shell--in-flight nil))
        (opencode-shell-resync)
        (should (equal (mapcar #'car requests) '("/session/s/message")))))))

(ert-deftest opencode-shell-capabilities-retry-after-transient-failure ()
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--session-id "s" opencode-shell--generation 1)
    (let (requests)
      (cl-letf (((symbol-function 'opencode-shell--request)
                 (lambda (_method path callback &optional _body _params error-callback)
                   (push (list path callback error-callback) requests))))
        (opencode-shell-resync)
        (funcall (nth 2 (assoc "/provider" requests)))
        (should opencode-shell--capabilities-loading)
        (funcall (cadr (assoc "/agent" requests)) nil)
        (should-not opencode-shell--capabilities-loading)
        (should-not opencode-shell--capabilities-loaded)
        (setq requests nil)
        (opencode-shell-resync)
        ;; The still-pending message poll remains guarded; only the failed
        ;; capability batch is retried.
        (should (= (length requests) 2))
        (should (assoc "/provider" requests))
        (should (assoc "/agent" requests))))))

(ert-deftest opencode-shell-poll-error-releases-guard ()
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--generation 7)
    (let (failed)
      (cl-letf (((symbol-function 'opencode-shell--request)
                 (lambda (_method _path _callback &optional _body _params error-callback)
                   (setq failed error-callback))))
        (opencode-shell--guarded-request 'messages "GET" "/message" #'ignore)
        (should (alist-get 'messages opencode-shell--in-flight))
        (funcall failed)
        (should-not (alist-get 'messages opencode-shell--in-flight))))))

(ert-deftest opencode-shell-request-ignores-killed-origin ()
  (let ((origin (generate-new-buffer " *oc-dead-origin*")) retrieve-callback called)
    (cl-letf (((symbol-function 'url-retrieve)
               (lambda (_url callback &rest _)
                 (setq retrieve-callback callback))))
      (with-current-buffer origin
        (opencode-shell--request "GET" "/late" (lambda (_) (setq called t))))
      (kill-buffer origin)
      (with-temp-buffer
        (insert "HTTP/1.1 200 OK\r\n\r\n[]")
        (setq-local url-http-response-status 200)
        (funcall retrieve-callback nil))
      (should-not called))))

(ert-deftest opencode-shell-reopen-keeps-one-timer ()
  (let (timers cancelled)
    (cl-letf (((symbol-function 'pop-to-buffer) #'ignore)
              ((symbol-function 'opencode-shell-resync) #'ignore)
              ((symbol-function 'run-at-time)
               (lambda (&rest _) (let ((timer (list 'timer))) (push timer timers) timer)))
              ((symbol-function 'timerp) (lambda (value) (eq (car-safe value) 'timer)))
              ((symbol-function 'cancel-timer) (lambda (timer) (push timer cancelled))))
      (unwind-protect
          (progn
            (opencode-shell-open-session "timer-test")
            (opencode-shell-open-session "timer-test")
            (should (= (length timers) 2))
            (should (equal cancelled (list (cadr timers)))))
        (kill-buffer "*OpenCode Shell timer-test*")))))

(ert-deftest opencode-shell-evil-setup-load-orders ()
  (let (calls)
    (cl-letf (((symbol-function 'evil-set-initial-state)
               (lambda (&rest args) (push (cons 'state args) calls)))
              ((symbol-function 'evil-define-key*)
               (lambda (&rest args) (push (cons 'key args) calls))))
      (opencode-shell--setup-evil)
      (should (= (length calls) 4)))))

(ert-deftest opencode-shell-selections-are-buffer-local ()
  (let ((a (generate-new-buffer " *oc-a*")) (b (generate-new-buffer " *oc-b*")))
    (unwind-protect
        (progn
          (with-current-buffer a (opencode-shell-mode)
                               (setq opencode-shell--selected-agent "build"))
          (with-current-buffer b (opencode-shell-mode)
                               (should-not opencode-shell--selected-agent)))
      (kill-buffer a) (kill-buffer b))))

(ert-deftest opencode-shell-markdown-preserves-raw-unicode-and-fences ()
  (with-temp-buffer
    (setq font-lock-defaults '(opencode-shell-render-font-lock-keywords t))
    (let ((raw "# 제목\n\n- 목록과 **굵게** 및 [링크](https://example.com)\n\n> 원문\n\n```elisp\n(message \"안녕\")\n```\n"))
      (opencode-shell-render-insert raw)
      (should (equal (buffer-substring-no-properties (point-min) (point-max)) raw))
      (should (get-text-property (string-match "message" raw) 'face)))))

(ert-deftest opencode-shell-keymaps-and-cleanup ()
  (should (eq (lookup-key opencode-shell-mode-map (kbd "p")) #'opencode-shell-prompt))
  (should (eq (lookup-key opencode-shell-sessions-mode-map (kbd "RET"))
              #'opencode-shell-open-at-point))
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--poll-timer (run-at-time 60 nil #'ignore))
    (setq opencode-shell--generation 4
          opencode-shell--in-flight '((messages . t))
          opencode-shell--capabilities-loading t)
    (opencode-shell--cleanup)
    (should-not opencode-shell--poll-timer)
    (should-not opencode-shell--in-flight)
    (should-not opencode-shell--capabilities-loading)
    (should (= opencode-shell--generation 5))))

;; Profile and server lifecycle contract.  These tests intentionally use
;; complete profile plists: a profile is an immutable piece of configuration,
;; while resolved credentials and process ownership are transient state.

(defconst opencode-shell-test--local-profile
  '(:name "local" :base-url "http://127.0.0.1:7777/"
    :directory "/client/project" :workspace "/server/project"
    :start-command ("opencode" "serve") :server-directory "/tmp"
    :startup-timeout 2 :auth-source (:host "localhost" :port 7777)))

(defconst opencode-shell-test--remote-profile
  '(:name "remote" :base-url "https://code.example.test"
    :directory "/ssh:code.example.test:/srv/project"
    :workspace "/srv/project" :start-command ("opencode" "serve")))

(ert-deftest opencode-shell-profile-helpers-are-defined-before-public-commands ()
  (dolist (symbol '(opencode-shell--profile-key opencode-shell--profile-name
                    opencode-shell--default-profile opencode-shell--read-profile
                    opencode-shell--matching-profile opencode-shell--profile-remote-p))
    (should (fboundp symbol)))
  (should (boundp 'opencode-shell-profiles))
  (should (boundp 'opencode-shell--servers)))

(ert-deftest opencode-shell-profile-key-name-default-read-and-match ()
  (let ((opencode-shell-profiles
         (list opencode-shell-test--local-profile
               opencode-shell-test--remote-profile))
        (default-directory "/client/project/src/") choice)
    (should (equal (opencode-shell--profile-name opencode-shell-test--local-profile)
                   "local"))
    (should (equal (opencode-shell--profile-key opencode-shell-test--local-profile)
                   (opencode-shell--profile-key (copy-tree opencode-shell-test--local-profile))))
    (should (equal (opencode-shell--default-profile)
                   (list :name "default" :base-url opencode-shell-base-url
                         :directory opencode-shell-directory)))
    (should (equal (opencode-shell--matching-profile)
                   opencode-shell-test--local-profile))
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_prompt candidates &rest _)
                 (setq choice candidates) "remote")))
      (should (equal (opencode-shell--read-profile)
                     opencode-shell-test--remote-profile))
      (let ((names (mapcar (lambda (item) (if (consp item) (car item) item)) choice)))
        (should (member "local" names))
        (should (member "remote" names))))))

(ert-deftest opencode-shell-profile-local-and-tramp-directory-mapping ()
  (should-not (opencode-shell--profile-remote-p opencode-shell-test--local-profile))
  (should (opencode-shell--profile-remote-p opencode-shell-test--remote-profile))
  (should (equal (opencode-shell--server-directory
                  "/client/project/src/a.el" opencode-shell-test--local-profile)
                 "/server/project/src/a.el"))
  (should (equal (opencode-shell--server-directory
                  "/ssh:code.example.test:/srv/project/src/a.el"
                  opencode-shell-test--remote-profile)
                 "/srv/project/src/a.el")))

(ert-deftest opencode-shell-profile-scopes-url-directory-workspace-and-auth ()
  (let ((opencode-shell-auth-source-function
         (lambda (profile)
           (should (equal profile opencode-shell-test--local-profile))
           "Bearer profile-secret"))
        captured-url captured-headers messages)
    (with-temp-buffer
      (setq-local opencode-shell--profile opencode-shell-test--local-profile)
      (setq-local opencode-shell--directory "/server/project")
      (cl-letf (((symbol-function 'url-retrieve)
                 (lambda (url _callback &rest _)
                   (setq captured-url url captured-headers url-request-extra-headers)))
                ((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (push (apply #'format format-string args) messages))))
        (opencode-shell--request "GET" "/session" #'ignore)))
    (should (string-prefix-p "http://127.0.0.1:7777/session?" captured-url))
    (should (string-match-p "directory=%2Fserver%2Fproject" captured-url))
    (should (equal (cdr (assoc "Authorization" captured-headers))
                   "Bearer profile-secret"))
    (should-not (string-match-p "profile-secret"
                                (format "%S%S" opencode-shell-test--local-profile messages)))))

(ert-deftest opencode-shell-launch-and-open-profile-preserve-session-isolation ()
  (let (opened)
    (cl-letf (((symbol-function 'opencode-shell--matching-profile)
               (lambda () opencode-shell-test--local-profile))
              ((symbol-function 'opencode-shell-start-server)
               (lambda (profile callback) (funcall callback profile)))
              ((symbol-function 'opencode-shell-sessions)
               (lambda (&optional directory profile)
                 (setq opened (list directory profile)))))
      (opencode-shell-launch)
      (should (equal opened (list nil opencode-shell-test--local-profile))))
    (let ((opencode-shell-poll-interval 60) buffers)
      (cl-letf (((symbol-function 'pop-to-buffer) (lambda (buffer &rest _) (push buffer buffers)))
                ((symbol-function 'opencode-shell-resync) #'ignore)
                ((symbol-function 'run-at-time) (lambda (&rest _) nil)))
        (unwind-protect
            (progn
              (opencode-shell-open-session "same-id" nil opencode-shell-test--local-profile)
              (opencode-shell-open-session "same-id" nil opencode-shell-test--remote-profile)
              (should (= (length (delete-dups buffers)) 2)))
          (mapc (lambda (buffer) (when (buffer-live-p buffer) (kill-buffer buffer))) buffers))))))

(ert-deftest opencode-shell-sessions-remains-backward-compatible ()
  (let (seen)
    (cl-letf (((symbol-function 'pop-to-buffer) #'ignore)
              ((symbol-function 'opencode-shell-refresh)
               (lambda () (push (list opencode-shell--directory opencode-shell--profile) seen))))
      (unwind-protect
          (progn
            (opencode-shell-sessions "/legacy/directory")
            (should (equal (caar seen) "/legacy/directory"))
            (opencode-shell-sessions opencode-shell-test--remote-profile)
            (should (equal (cadar seen) opencode-shell-test--remote-profile))
            (opencode-shell-sessions "/explicit" opencode-shell-test--local-profile)
            (should (equal (car seen)
                           (list "/explicit" opencode-shell-test--local-profile))))
        (when-let ((buffer (get-buffer "*OpenCode Shell Sessions*"))) (kill-buffer buffer))))))

(ert-deftest opencode-shell-server-health-reuse-does-not-spawn ()
  (let ((opencode-shell--servers (make-hash-table :test #'equal)) spawned callback)
    (cl-letf (((symbol-function 'opencode-shell--server-ready)
               (lambda (profile ready) (funcall ready profile)))
              ((symbol-function 'make-process) (lambda (&rest _) (setq spawned t))))
      (opencode-shell-start-server opencode-shell-test--local-profile
                                    (lambda (profile) (setq callback profile))))
    (should-not spawned)
    (should (equal callback opencode-shell-test--local-profile))))

(ert-deftest opencode-shell-server-start-is-single-per-profile-and-let-binds-directory ()
  (let ((opencode-shell--servers (make-hash-table :test #'equal))
        (make-calls 0) process-directory timers health-callback)
    (cl-letf (((symbol-function 'opencode-shell--server-ready)
               (lambda (_profile callback) (setq health-callback callback)))
              ((symbol-function 'make-process)
               (lambda (&rest _)
                 (cl-incf make-calls) (setq process-directory default-directory) 'fake-process))
              ((symbol-function 'process-live-p) (lambda (_) t))
              ((symbol-function 'run-at-time)
               (lambda (&rest args) (push args timers) 'fake-timer)))
      (opencode-shell-start-server opencode-shell-test--local-profile #'ignore)
      (opencode-shell-start-server opencode-shell-test--local-profile #'ignore)
      (funcall health-callback nil)
      (funcall health-callback nil))
    (should (= make-calls 1))
    (should (equal (directory-file-name process-directory) "/tmp"))
    (should timers)))

(ert-deftest opencode-shell-server-wait-is-bounded ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (key (opencode-shell--profile-key opencode-shell-test--local-profile))
         scheduled messages)
    (puthash key (list :callbacks (list #'ignore) :starting t)
             opencode-shell--servers)
    (cl-letf (((symbol-function 'float-time) (lambda (&optional _) 20.0))
              ((symbol-function 'run-at-time) (lambda (&rest args) (push args scheduled)))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (push (apply #'format format-string args) messages))))
      (opencode-shell--await-server opencode-shell-test--local-profile 10.0))
    (should-not scheduled)
    (should-not (plist-get (gethash key opencode-shell--servers) :callbacks))
    (should (string-match-p "timed out" (car messages)))))

(ert-deftest opencode-shell-explicit-stop-restart-and-owned-only-stop ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (profile opencode-shell-test--local-profile)
         (key (opencode-shell--profile-key profile)) deleted started)
    (puthash key (list :process 'owned :owned t) opencode-shell--servers)
    (cl-letf (((symbol-function 'process-live-p) (lambda (process) (eq process 'owned)))
              ((symbol-function 'delete-process) (lambda (process) (setq deleted process))))
      (opencode-shell-stop-server profile))
    (should (eq deleted 'owned))
    (should-not (gethash key opencode-shell--servers))
    (puthash key (list :process 'foreign :owned nil) opencode-shell--servers)
    (should-error (opencode-shell-stop-server profile) :type 'user-error)
    (puthash key (list :process 'owned :owned t) opencode-shell--servers)
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) t))
              ((symbol-function 'delete-process) #'ignore)
              ((symbol-function 'opencode-shell-start-server)
               (lambda (value &rest _) (setq started value))))
      (opencode-shell-restart-server profile))
    (should (equal started profile))))

(ert-deftest opencode-shell-remote-profile-never-autostarts ()
  (let ((opencode-shell--servers (make-hash-table :test #'equal)) spawned)
    (cl-letf (((symbol-function 'make-process) (lambda (&rest _) (setq spawned t))))
      (opencode-shell-start-server opencode-shell-test--remote-profile #'ignore))
    (should-not spawned)
    (should (= (hash-table-count opencode-shell--servers) 0))))

(ert-deftest opencode-shell-killing-transcript-does-not-stop-owned-server ()
  (let* ((opencode-shell--servers (make-hash-table :test #'equal))
         (profile opencode-shell-test--local-profile)
         (key (opencode-shell--profile-key profile)) stopped)
    (puthash key (list :process 'owned :owned t) opencode-shell--servers)
    (with-temp-buffer
      (opencode-shell-mode)
      (setq-local opencode-shell--profile profile)
      (cl-letf (((symbol-function 'delete-process) (lambda (&rest _) (setq stopped t))))
        (opencode-shell--cleanup)))
    (should-not stopped)
    (should (gethash key opencode-shell--servers))))

(ert-deftest opencode-shell-health-probe-is-async-and-coalesced ()
  (let ((opencode-shell--servers (make-hash-table :test #'equal)) probe (spawned 0))
    (cl-letf (((symbol-function 'opencode-shell--server-ready)
               (lambda (_profile callback) (setq probe callback)))
              ((symbol-function 'opencode-shell--spawn-server)
               (lambda (_) (cl-incf spawned))))
      (opencode-shell-start-server opencode-shell-test--local-profile #'ignore)
      (opencode-shell-start-server opencode-shell-test--local-profile #'ignore)
      (should (= spawned 0))
      (funcall probe nil)
      (should (= spawned 1)))))

(ert-deftest opencode-shell-browser-state-is-buffer-and-generation-isolated ()
  (let ((one (generate-new-buffer " *oc-one*"))
        (two (generate-new-buffer " *oc-two*")) requests)
    (unwind-protect
        (cl-letf (((symbol-function 'opencode-shell--request)
                   (lambda (_method path callback &rest _)
                     (push (list (current-buffer) path callback) requests))))
          (dolist (buffer (list one two))
            (with-current-buffer buffer
              (opencode-shell-sessions-mode)
              (opencode-shell-refresh)))
          (dolist (request (copy-sequence requests))
            (when (equal (cadr request) "/session/status")
              (with-current-buffer (car request)
                (funcall (nth 2 request)
                         `((,(if (eq (car request) one) "one" "two")
                            . ((type . "busy"))))))))
          (dolist (request requests)
            (when (equal (cadr request) "/session")
              (with-current-buffer (car request)
                (funcall (nth 2 request)
                         `(((id . ,(if (eq (car request) one) "one" "two"))))))))
          (should (equal (with-current-buffer one (opencode-shell--get
                                                   opencode-shell--session-status "one"))
                         '((type . "busy"))))
          (should (equal (with-current-buffer one
                           (opencode-shell--get (car opencode-shell--sessions) 'id)) "one"))
          (should (equal (with-current-buffer two
                           (opencode-shell--get (car opencode-shell--sessions) 'id)) "two")))
      (kill-buffer one) (kill-buffer two))))

(ert-deftest opencode-shell-profile-specificity-regexp-and-validation ()
  (let ((opencode-shell-profiles
         '((:name "broad" :base-url "http://localhost:1" :match "/work")
           (:name "specific" :base-url "http://localhost:2" :match "/work/app")
           (:name "regexp" :base-url "http://localhost:3" :match-regexp "^/special/"))))
    (should (equal (plist-get (opencode-shell--matching-profile "/work/app/src") :name)
                   "specific"))
    (should (equal (plist-get (opencode-shell--matching-profile "/special/x") :name)
                   "regexp")))
  (let ((opencode-shell-profiles
         '((:name "duplicate" :id "one") (:name "duplicate" :id "two"))))
    (should-error (opencode-shell--validate-profiles) :type 'user-error))
  (let ((opencode-shell-profiles
         '((:name "one" :id "same") (:name "two" :id "same"))))
    (should-error (opencode-shell--validate-profiles) :type 'user-error)))

(ert-deftest opencode-shell-custom-raw-auth-header-covers-health ()
  (let ((profile '(:name "auth" :base-url "http://localhost:9"
                   :auth-header "X-OpenCode-Token"))
        (opencode-shell-auth-source-function (lambda (_) "raw-secret")) headers)
    (cl-letf (((symbol-function 'url-retrieve)
               (lambda (_url _callback &rest _)
                 (setq headers url-request-extra-headers))))
      (opencode-shell--server-ready profile #'ignore))
    (should (equal (cdr (assoc "X-OpenCode-Token" headers)) "raw-secret"))
    (should-not (string-match-p "Bearer" (format "%S" headers)))))

(ert-deftest opencode-shell-process-tail-and-package-exit-cleanup ()
  (let ((buffer (generate-new-buffer " *oc-tail*")) deleted
        (opencode-shell--servers (make-hash-table :test #'equal)))
    (unwind-protect
        (cl-letf (((symbol-function 'process-buffer) (lambda (_) buffer))
                  ((symbol-function 'process-live-p) (lambda (_) t))
                  ((symbol-function 'delete-process) (lambda (p) (push p deleted))))
          (opencode-shell--process-filter 'process (make-string 5000 ?x))
          (should (<= (with-current-buffer buffer (buffer-size))
                      opencode-shell--process-tail-limit))
          (puthash "one" '(:process owned :owned t) opencode-shell--servers)
          (puthash "two" '(:process foreign :owned nil) opencode-shell--servers)
          (opencode-shell-stop-all-servers)
          (should (equal deleted '(owned)))
          (should (= (hash-table-count opencode-shell--servers) 0)))
      (kill-buffer buffer))))

(ert-deftest opencode-shell-make-process-error-clears-start-state ()
  (let ((opencode-shell--servers (make-hash-table :test #'equal)) messages)
    (cl-letf (((symbol-function 'make-process) (lambda (&rest _) (error "spawn failed")))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (push (apply #'format format-string args) messages))))
      (puthash (opencode-shell--profile-key opencode-shell-test--local-profile)
               '(:starting t :callbacks (ignore)) opencode-shell--servers)
      (opencode-shell--spawn-server opencode-shell-test--local-profile))
    (should (= (hash-table-count opencode-shell--servers) 0))
    (should (string-match-p "could not start server" (car messages)))))

(provide 'opencode-shell-test)
;;; opencode-shell-test.el ends here
