;;; opencode-shell-acceptance-test.el --- Workflow acceptance tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'opencode-shell)

(defun opencode-shell-acceptance--messages (count)
  "Return COUNT complete chronological conversation turns."
  (apply #'append
         (cl-loop for n from 1 to count
                  collect `(((info . ((id . ,(format "u%d" n)) (role . "user")))
                             (parts . (((type . "text")
                                        (text . ,(format "질문 %d" n))))))
                            ((info . ((id . ,(format "a%d" n))
                                      (role . "assistant")
                                      (parentID . ,(format "u%d" n))
                                      (finish . "stop")
                                      (time . ((completed . ,n)))))
                             (parts . (((id . ,(format "a%d-text" n))
                                        (type . "text")
                                        (text . ,(format "응답 %d" n))))))))))

(ert-deftest opencode-shell-acceptance-ten-turn-conversation ()
  (with-temp-buffer
    (opencode-shell-mode)
    (setq opencode-shell--session-id "acceptance")
    (let (success)
      (cl-letf (((symbol-function 'opencode-shell--request)
                 (lambda (_method _path callback &optional _body _params _error)
                   (setq success callback))))
        (dotimes (index 10)
          (goto-char (point-max))
          (insert (format "질문 %d" (1+ index)))
          (opencode-shell--submit)
          (funcall success nil)
          (opencode-shell--render-messages
           (opencode-shell-acceptance--messages (1+ index)))
          (should (= (length opencode-shell--turns) (1+ index)))
          (should (string-empty-p (opencode-shell--composer-text)))
          (should (= (point) opencode-shell--composer-start))
          (should (eq (get-text-property (point-min) 'read-only) t)))))))

(ert-deftest opencode-shell-acceptance-insert-entry-focuses-composer ()
  (dolist (_command '(i I a A o O))
    (with-temp-buffer
      (opencode-shell-mode)
      (let ((inhibit-read-only t))
        (goto-char (point-min)))
      (opencode-shell--evil-move-to-composer)
      (should (= (point) (point-max)))
      (should (opencode-shell--in-composer-p)))))

(ert-deftest opencode-shell-acceptance-queued-response-preserves-active-draft ()
  (with-temp-buffer
    (opencode-shell-mode)
    (let (visible)
      (goto-char (point-max))
      (insert "작성 중인 초안")
      (cl-letf (((symbol-function 'get-buffer-window)
                 (lambda (&rest _) visible)))
        (opencode-shell--render-messages
         (opencode-shell-acceptance--messages 2) 1 t)
        (should (equal (opencode-shell--composer-text) "작성 중인 초안"))
        (setq visible t)
        (opencode-shell--render-if-visible)
        (opencode-shell-async-drain (current-buffer))
        (should (equal (opencode-shell--composer-text) "작성 중인 초안"))))))

(ert-deftest opencode-shell-acceptance-shared-runtime-coalesces-and-falls-back ()
  (let ((opencode-shell-async--runtimes (make-hash-table :test #'equal))
        (first (generate-new-buffer " *accept-runtime-1*"))
        (second (generate-new-buffer " *accept-runtime-2*"))
        (runtime (list :subscribers (make-hash-table :test #'eq)
                       :sse-input "" :connected t :ticks 0
                       :poll-interval 2))
        (first-wakes 0) (second-wakes 0))
    (unwind-protect
        (cl-letf (((symbol-function 'run-with-idle-timer)
                   (lambda (&rest _) 'idle-timer))
                  ((symbol-function 'timerp)
                   (lambda (value) (eq value 'idle-timer)))
                  ((symbol-function 'cancel-timer) #'ignore))
          (dolist (buffer (list first second))
            (with-current-buffer buffer
              (setq-local opencode-shell--generation 1)))
          (puthash first (lambda () (cl-incf first-wakes))
                   (plist-get runtime :subscribers))
          (puthash second (lambda () (cl-incf second-wakes))
                   (plist-get runtime :subscribers))
          (puthash 'accept runtime opencode-shell-async--runtimes)
          (dolist (frame opencode-shell-test--sse-wake-burst)
            (opencode-shell-async--parse-sse runtime frame))
          (opencode-shell-async-drain first)
          (opencode-shell-async-drain second)
          (should (= first-wakes 1))
          (should (= second-wakes 1))
          (setf (plist-get runtime :connected) nil)
          (opencode-shell-async--poll-runtime 'accept)
          (opencode-shell-async-drain first)
          (opencode-shell-async-drain second)
          (should (= first-wakes 2))
          (should (= second-wakes 2)))
      (kill-buffer first)
      (kill-buffer second))))

(provide 'opencode-shell-acceptance-test)
;;; opencode-shell-acceptance-test.el ends here
